# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './qtarmsim/ui/mainwindow.ui',
# licensing of './qtarmsim/ui/mainwindow.ui' applies.
#
# Created: Tue May  5 11:22:14 2020
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(925, 712)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowTitle("QtARMSim")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(True)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowNestedDocks|QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidgetCode = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidgetCode.sizePolicy().hasHeightForWidth())
        self.tabWidgetCode.setSizePolicy(sizePolicy)
        self.tabWidgetCode.setMinimumSize(QtCore.QSize(400, 300))
        self.tabWidgetCode.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidgetCode.setObjectName("tabWidgetCode")
        self.tabSource = QtWidgets.QWidget()
        self.tabSource.setObjectName("tabSource")
        self.verticalLayoutSource = QtWidgets.QVBoxLayout(self.tabSource)
        self.verticalLayoutSource.setObjectName("verticalLayoutSource")
        self.tabWidgetCode.addTab(self.tabSource, "")
        self.tabARMSim = QtWidgets.QWidget()
        self.tabARMSim.setAccessibleName("")
        self.tabARMSim.setObjectName("tabARMSim")
        self.verticalLayoutARMSim = QtWidgets.QVBoxLayout(self.tabARMSim)
        self.verticalLayoutARMSim.setObjectName("verticalLayoutARMSim")
        self.tabTabARMSim = QtWidgets.QTabWidget(self.tabARMSim)
        self.tabTabARMSim.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabTabARMSim.setObjectName("tabTabARMSim")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabTabARMSim.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabTabARMSim.addTab(self.tab_4, "")
        self.verticalLayoutARMSim.addWidget(self.tabTabARMSim)
        self.tabWidgetCode.addTab(self.tabARMSim, "")
        self.verticalLayout.addWidget(self.tabWidgetCode)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 925, 32))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuExamples = QtWidgets.QMenu(self.menuFile)
        self.menuExamples.setObjectName("menuExamples")
        self.menuRun = QtWidgets.QMenu(self.menubar)
        self.menuRun.setObjectName("menuRun")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menu_Window = QtWidgets.QMenu(self.menubar)
        self.menu_Window.setObjectName("menu_Window")
        self.menu_Edit = QtWidgets.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidgetRegisters = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetRegisters.sizePolicy().hasHeightForWidth())
        self.dockWidgetRegisters.setSizePolicy(sizePolicy)
        self.dockWidgetRegisters.setMinimumSize(QtCore.QSize(180, 126))
        self.dockWidgetRegisters.setToolTip("")
        self.dockWidgetRegisters.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidgetRegisters.setObjectName("dockWidgetRegisters")
        self.dockWidgetContentsRegisters = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContentsRegisters.sizePolicy().hasHeightForWidth())
        self.dockWidgetContentsRegisters.setSizePolicy(sizePolicy)
        self.dockWidgetContentsRegisters.setObjectName("dockWidgetContentsRegisters")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.dockWidgetContentsRegisters)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.treeViewRegisters = MyQTreeView(self.dockWidgetContentsRegisters)
        self.treeViewRegisters.setEnabled(True)
        self.treeViewRegisters.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.treeViewRegisters.setFrameShadow(QtWidgets.QFrame.Plain)
        self.treeViewRegisters.setLineWidth(0)
        self.treeViewRegisters.setAlternatingRowColors(True)
        self.treeViewRegisters.setObjectName("treeViewRegisters")
        self.verticalLayout_6.addWidget(self.treeViewRegisters)
        self.dockWidgetRegisters.setWidget(self.dockWidgetContentsRegisters)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidgetRegisters)
        self.dockWidgetMemory = QtWidgets.QDockWidget(MainWindow)
        self.dockWidgetMemory.setMinimumSize(QtCore.QSize(180, 126))
        self.dockWidgetMemory.setToolTip("")
        self.dockWidgetMemory.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidgetMemory.setObjectName("dockWidgetMemory")
        self.dockWidgetContentsMemory = QtWidgets.QWidget()
        self.dockWidgetContentsMemory.setObjectName("dockWidgetContentsMemory")
        self.dockWidgetMemoryLayout = QtWidgets.QVBoxLayout(self.dockWidgetContentsMemory)
        self.dockWidgetMemoryLayout.setObjectName("dockWidgetMemoryLayout")
        self.treeViewMemory = MyQTreeView(self.dockWidgetContentsMemory)
        self.treeViewMemory.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.treeViewMemory.setFrameShadow(QtWidgets.QFrame.Plain)
        self.treeViewMemory.setLineWidth(0)
        self.treeViewMemory.setAlternatingRowColors(True)
        self.treeViewMemory.setObjectName("treeViewMemory")
        self.dockWidgetMemoryLayout.addWidget(self.treeViewMemory)
        self.dockWidgetMemory.setWidget(self.dockWidgetContentsMemory)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidgetMemory)
        self.dockWidgetMessages = QtWidgets.QDockWidget(MainWindow)
        self.dockWidgetMessages.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea)
        self.dockWidgetMessages.setObjectName("dockWidgetMessages")
        self.dockWidgetMessagesContents = QtWidgets.QWidget()
        self.dockWidgetMessagesContents.setObjectName("dockWidgetMessagesContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.dockWidgetMessagesContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.textEditMessages = QtWidgets.QTextEdit(self.dockWidgetMessagesContents)
        self.textEditMessages.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditMessages.sizePolicy().hasHeightForWidth())
        self.textEditMessages.setSizePolicy(sizePolicy)
        self.textEditMessages.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textEditMessages.setWhatsThis("")
        self.textEditMessages.setDocumentTitle("")
        self.textEditMessages.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEditMessages.setObjectName("textEditMessages")
        self.verticalLayout_5.addWidget(self.textEditMessages)
        self.dockWidgetMessages.setWidget(self.dockWidgetMessagesContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidgetMessages)
        self.dockWidgetMemoryDump = QtWidgets.QDockWidget(MainWindow)
        self.dockWidgetMemoryDump.setObjectName("dockWidgetMemoryDump")
        self.dockWidgetMemoryDumpContents = QtWidgets.QWidget()
        self.dockWidgetMemoryDumpContents.setObjectName("dockWidgetMemoryDumpContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetMemoryDumpContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidgetMemoryDump = QtWidgets.QTabWidget(self.dockWidgetMemoryDumpContents)
        self.tabWidgetMemoryDump.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidgetMemoryDump.setObjectName("tabWidgetMemoryDump")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidgetMemoryDump.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidgetMemoryDump.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidgetMemoryDump)
        self.dockWidgetMemoryDump.setWidget(self.dockWidgetMemoryDumpContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidgetMemoryDump)
        self.dockWidgetLCDDisplay = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetLCDDisplay.sizePolicy().hasHeightForWidth())
        self.dockWidgetLCDDisplay.setSizePolicy(sizePolicy)
        self.dockWidgetLCDDisplay.setObjectName("dockWidgetLCDDisplay")
        self.dockWidgetLCDContents = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetLCDContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetLCDContents.setSizePolicy(sizePolicy)
        self.dockWidgetLCDContents.setObjectName("dockWidgetLCDContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dockWidgetLCDContents)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.dockWidgetLCDContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 360, 234))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.memoryLCDView = MemoryLCDView(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memoryLCDView.sizePolicy().hasHeightForWidth())
        self.memoryLCDView.setSizePolicy(sizePolicy)
        self.memoryLCDView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.memoryLCDView.setObjectName("memoryLCDView")
        self.horizontalLayout_4.addWidget(self.memoryLCDView)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.dockWidgetLCDDisplay.setWidget(self.dockWidgetLCDContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidgetLCDDisplay)
        self.dockWidgetTerminal = QtWidgets.QDockWidget(MainWindow)
        self.dockWidgetTerminal.setObjectName("dockWidgetTerminal")
        self.dockWidgetTerminalContents = QtWidgets.QWidget()
        self.dockWidgetTerminalContents.setObjectName("dockWidgetTerminalContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetTerminalContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textBrowserTerminal = QtWidgets.QTextBrowser(self.dockWidgetTerminalContents)
        self.textBrowserTerminal.setObjectName("textBrowserTerminal")
        self.verticalLayout_3.addWidget(self.textBrowserTerminal)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditTerminal = QtWidgets.QLineEdit(self.dockWidgetTerminalContents)
        self.lineEditTerminal.setObjectName("lineEditTerminal")
        self.horizontalLayout_2.addWidget(self.lineEditTerminal)
        self.pushButtonTerminal = QtWidgets.QPushButton(self.dockWidgetTerminalContents)
        self.pushButtonTerminal.setObjectName("pushButtonTerminal")
        self.horizontalLayout_2.addWidget(self.pushButtonTerminal)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.dockWidgetTerminal.setWidget(self.dockWidgetTerminalContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidgetTerminal)
        self.actionWhats_This = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":themes/breeze/32/help-whatsthis.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionWhats_This.setIcon(icon)
        self.actionWhats_This.setObjectName("actionWhats_This")
        self.actionAbout_Qt_ARMSim = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":themes/breeze/32/help-about.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionAbout_Qt_ARMSim.setIcon(icon1)
        self.actionAbout_Qt_ARMSim.setObjectName("actionAbout_Qt_ARMSim")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":themes/breeze/22/help-contents.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionHelp.setIcon(icon2)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout_ARMSim = QtWidgets.QAction(MainWindow)
        self.actionAbout_ARMSim.setIcon(icon1)
        self.actionAbout_ARMSim.setObjectName("actionAbout_ARMSim")
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":themes/breeze/32/document-new.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionNew.setIcon(icon3)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":themes/breeze/32/document-open.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionOpen.setIcon(icon4)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":themes/breeze/32/document-save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSave.setIcon(icon5)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":themes/breeze/32/document-save-as.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSave_As.setIcon(icon6)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":themes/breeze/32/document-print.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPrint.setIcon(icon7)
        self.actionPrint.setObjectName("actionPrint")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":themes/breeze/32/application-exit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionQuit.setIcon(icon8)
        self.actionQuit.setObjectName("actionQuit")
        self.actionRun = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap(":themes/breeze/24/system-run.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionRun.setIcon(icon9)
        self.actionRun.setObjectName("actionRun")
        self.actionStepInto = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon10.addPixmap(QtGui.QPixmap(":themes/breeze/24/debug-step-into.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionStepInto.setIcon(icon10)
        self.actionStepInto.setObjectName("actionStepInto")
        self.actionShow_Statusbar = QtWidgets.QAction(MainWindow)
        self.actionShow_Statusbar.setCheckable(True)
        self.actionShow_Statusbar.setChecked(True)
        self.actionShow_Statusbar.setObjectName("actionShow_Statusbar")
        self.actionShow_Toolbar = QtWidgets.QAction(MainWindow)
        self.actionShow_Toolbar.setCheckable(True)
        self.actionShow_Toolbar.setChecked(True)
        self.actionShow_Toolbar.setObjectName("actionShow_Toolbar")
        self.actionShow_Registers = QtWidgets.QAction(MainWindow)
        self.actionShow_Registers.setCheckable(True)
        self.actionShow_Registers.setChecked(True)
        self.actionShow_Registers.setObjectName("actionShow_Registers")
        self.actionShow_Memory = QtWidgets.QAction(MainWindow)
        self.actionShow_Memory.setCheckable(True)
        self.actionShow_Memory.setChecked(True)
        self.actionShow_Memory.setObjectName("actionShow_Memory")
        self.actionRestore_Default_Layout = QtWidgets.QAction(MainWindow)
        self.actionRestore_Default_Layout.setObjectName("actionRestore_Default_Layout")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.action_Undo = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon11.addPixmap(QtGui.QPixmap(":themes/breeze/32/edit-undo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_Undo.setIcon(icon11)
        self.action_Undo.setObjectName("action_Undo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon12.addPixmap(QtGui.QPixmap(":themes/breeze/32/edit-redo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionRedo.setIcon(icon12)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCut = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon13.addPixmap(QtGui.QPixmap(":themes/breeze/24/edit-cut.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCut.setIcon(icon13)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon14.addPixmap(QtGui.QPixmap(":themes/breeze/24/edit-copy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCopy.setIcon(icon14)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon15.addPixmap(QtGui.QPixmap(":themes/breeze/24/edit-paste.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPaste.setIcon(icon15)
        self.actionPaste.setObjectName("actionPaste")
        self.actionSelect_All = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon16.addPixmap(QtGui.QPixmap(":themes/breeze/24/edit-select-all.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSelect_All.setIcon(icon16)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.actionShow_Messages = QtWidgets.QAction(MainWindow)
        self.actionShow_Messages.setCheckable(True)
        self.actionShow_Messages.setChecked(True)
        self.actionShow_Messages.setObjectName("actionShow_Messages")
        self.actionStepOver = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon17.addPixmap(QtGui.QPixmap(":themes/breeze/24/debug-step-over.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionStepOver.setIcon(icon17)
        self.actionStepOver.setObjectName("actionStepOver")
        self.actionRestart = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon18.addPixmap(QtGui.QPixmap(":themes/breeze/32/view-refresh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionRestart.setIcon(icon18)
        self.actionRestart.setObjectName("actionRestart")
        self.actionShow_Memory_Dump = QtWidgets.QAction(MainWindow)
        self.actionShow_Memory_Dump.setCheckable(True)
        self.actionShow_Memory_Dump.setChecked(True)
        self.actionShow_Memory_Dump.setObjectName("actionShow_Memory_Dump")
        self.actionShow_LCD_Display = QtWidgets.QAction(MainWindow)
        self.actionShow_LCD_Display.setCheckable(True)
        self.actionShow_LCD_Display.setChecked(True)
        self.actionShow_LCD_Display.setObjectName("actionShow_LCD_Display")
        self.actionShow_Terminal = QtWidgets.QAction(MainWindow)
        self.actionShow_Terminal.setCheckable(True)
        self.actionShow_Terminal.setChecked(True)
        self.actionShow_Terminal.setObjectName("actionShow_Terminal")
        self.actionadd = QtWidgets.QAction(MainWindow)
        self.actionadd.setObjectName("actionadd")
        self.actionadd_2 = QtWidgets.QAction(MainWindow)
        self.actionadd_2.setObjectName("actionadd_2")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.menuExamples.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuRun.addAction(self.actionRun)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.actionStepInto)
        self.menuRun.addAction(self.actionStepOver)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.actionRestart)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionWhats_This)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout_Qt_ARMSim)
        self.menuHelp.addAction(self.actionAbout_ARMSim)
        self.menu_Window.addAction(self.actionShow_Statusbar)
        self.menu_Window.addAction(self.actionShow_Toolbar)
        self.menu_Window.addAction(self.actionShow_Registers)
        self.menu_Window.addAction(self.actionShow_Memory)
        self.menu_Window.addAction(self.actionShow_Messages)
        self.menu_Window.addAction(self.actionShow_Memory_Dump)
        self.menu_Window.addAction(self.actionShow_LCD_Display)
        self.menu_Window.addAction(self.actionShow_Terminal)
        self.menu_Window.addSeparator()
        self.menu_Window.addAction(self.actionRestore_Default_Layout)
        self.menu_Window.addSeparator()
        self.menu_Edit.addAction(self.action_Undo)
        self.menu_Edit.addAction(self.actionRedo)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.actionCut)
        self.menu_Edit.addAction(self.actionCopy)
        self.menu_Edit.addAction(self.actionPaste)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.actionSelect_All)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_Window.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Undo)
        self.toolBar.addAction(self.actionRedo)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRun)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStepInto)
        self.toolBar.addAction(self.actionStepOver)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRestart)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionWhats_This)

        self.retranslateUi(MainWindow)
        self.tabWidgetCode.setCurrentIndex(0)
        self.tabTabARMSim.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.tabSource.setWhatsThis(QtWidgets.QApplication.translate("MainWindow", "The Editor tab is used to edit the assembler  code that is going to be simmulated", None, -1))
        self.tabWidgetCode.setTabText(self.tabWidgetCode.indexOf(self.tabSource), QtWidgets.QApplication.translate("MainWindow", "Editor", None, -1))
        self.tabARMSim.setWhatsThis(QtWidgets.QApplication.translate("MainWindow", "The ArmSim tab is used to inspect and simmulate the ARM machine code generated after assembling the source code", None, -1))
        self.tabTabARMSim.setTabText(self.tabTabARMSim.indexOf(self.tab_3), QtWidgets.QApplication.translate("MainWindow", "Tab 1", None, -1))
        self.tabTabARMSim.setTabText(self.tabTabARMSim.indexOf(self.tab_4), QtWidgets.QApplication.translate("MainWindow", "Tab 2", None, -1))
        self.tabWidgetCode.setTabText(self.tabWidgetCode.indexOf(self.tabARMSim), QtWidgets.QApplication.translate("MainWindow", "ARMSim", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "&File", None, -1))
        self.menuExamples.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Examples", None, -1))
        self.menuRun.setTitle(QtWidgets.QApplication.translate("MainWindow", "R&un", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.menu_Window.setTitle(QtWidgets.QApplication.translate("MainWindow", "&View", None, -1))
        self.menu_Edit.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Edit", None, -1))
        self.toolBar.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Barra de herramientas", None, -1))
        self.dockWidgetRegisters.setWhatsThis(QtWidgets.QApplication.translate("MainWindow", "The Registers dock shows the contents of the registers", None, -1))
        self.dockWidgetRegisters.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Re&gisters", None, -1))
        self.dockWidgetMemory.setWhatsThis(QtWidgets.QApplication.translate("MainWindow", "The Memory dock shows the contents of the memory", None, -1))
        self.dockWidgetMemory.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "&Memory", None, -1))
        self.dockWidgetMessages.setWhatsThis(QtWidgets.QApplication.translate("MainWindow", "The Messages dock shows QtARMSim and ARMSim messages", None, -1))
        self.dockWidgetMessages.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Messages", None, -1))
        self.dockWidgetMemoryDump.setWhatsThis(QtWidgets.QApplication.translate("MainWindow", "The Memory Dump dock shows the memory dump of the simulated system", None, -1))
        self.dockWidgetMemoryDump.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Memory &Dump", None, -1))
        self.tabWidgetMemoryDump.setTabText(self.tabWidgetMemoryDump.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "Tab 1", None, -1))
        self.tabWidgetMemoryDump.setTabText(self.tabWidgetMemoryDump.indexOf(self.tab_2), QtWidgets.QApplication.translate("MainWindow", "Tab 2", None, -1))
        self.dockWidgetLCDDisplay.setWhatsThis(QtWidgets.QApplication.translate("MainWindow", "The LCD Display shows the output of a simulated LCD Display Device", None, -1))
        self.dockWidgetLCDDisplay.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "&LCD Display", None, -1))
        self.dockWidgetTerminal.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Termi&nal", None, -1))
        self.pushButtonTerminal.setText(QtWidgets.QApplication.translate("MainWindow", "Send command", None, -1))
        self.actionWhats_This.setText(QtWidgets.QApplication.translate("MainWindow", "What\'s &This?", None, -1))
        self.actionWhats_This.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "¿Qué es esto?", None, -1))
        self.actionWhats_This.setWhatsThis(QtWidgets.QApplication.translate("MainWindow", "Activa la ayuda", None, -1))
        self.actionWhats_This.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Shift+F1", None, -1))
        self.actionAbout_Qt_ARMSim.setText(QtWidgets.QApplication.translate("MainWindow", "&About QtARMSim", None, -1))
        self.actionAbout_Qt_ARMSim.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Sobre spim", None, -1))
        self.actionAbout_Qt_ARMSim.setWhatsThis(QtWidgets.QApplication.translate("MainWindow", "Imprime en el panel mensajes información sobre XSPIM", None, -1))
        self.actionHelp.setText(QtWidgets.QApplication.translate("MainWindow", "QtARMSim &Help", None, -1))
        self.actionHelp.setShortcut(QtWidgets.QApplication.translate("MainWindow", "F1", None, -1))
        self.actionAbout_ARMSim.setText(QtWidgets.QApplication.translate("MainWindow", "A&bout ARMSim", None, -1))
        self.actionNew.setText(QtWidgets.QApplication.translate("MainWindow", "&New...", None, -1))
        self.actionNew.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+N", None, -1))
        self.actionOpen.setText(QtWidgets.QApplication.translate("MainWindow", "&Open...", None, -1))
        self.actionOpen.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Open ARM assembler file", None, -1))
        self.actionOpen.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+O", None, -1))
        self.actionSave.setText(QtWidgets.QApplication.translate("MainWindow", "&Save", None, -1))
        self.actionSave.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+S", None, -1))
        self.actionSave_As.setText(QtWidgets.QApplication.translate("MainWindow", "Save &As...", None, -1))
        self.actionPrint.setText(QtWidgets.QApplication.translate("MainWindow", "&Print...", None, -1))
        self.actionPrint.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+P", None, -1))
        self.actionQuit.setText(QtWidgets.QApplication.translate("MainWindow", "&Quit", None, -1))
        self.actionQuit.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Q", None, -1))
        self.actionRun.setText(QtWidgets.QApplication.translate("MainWindow", "&Run", None, -1))
        self.actionRun.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+F11", None, -1))
        self.actionStepInto.setText(QtWidgets.QApplication.translate("MainWindow", "Step &Into", None, -1))
        self.actionStepInto.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Step Into", None, -1))
        self.actionStepInto.setShortcut(QtWidgets.QApplication.translate("MainWindow", "F5", None, -1))
        self.actionShow_Statusbar.setText(QtWidgets.QApplication.translate("MainWindow", "Show St&atusbar", None, -1))
        self.actionShow_Toolbar.setText(QtWidgets.QApplication.translate("MainWindow", "Show &Toolbar", None, -1))
        self.actionShow_Registers.setText(QtWidgets.QApplication.translate("MainWindow", "Show &Registers", None, -1))
        self.actionShow_Memory.setText(QtWidgets.QApplication.translate("MainWindow", "Show &Memory", None, -1))
        self.actionRestore_Default_Layout.setText(QtWidgets.QApplication.translate("MainWindow", "Rest&ore Default Layout", None, -1))
        self.actionRestore_Default_Layout.setShortcut(QtWidgets.QApplication.translate("MainWindow", "F3", None, -1))
        self.actionPreferences.setText(QtWidgets.QApplication.translate("MainWindow", "P&references...", None, -1))
        self.actionPreferences.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Alt+P", None, -1))
        self.action_Undo.setText(QtWidgets.QApplication.translate("MainWindow", "&Undo", None, -1))
        self.action_Undo.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Z", None, -1))
        self.actionRedo.setText(QtWidgets.QApplication.translate("MainWindow", "Re&do", None, -1))
        self.actionRedo.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+Z", None, -1))
        self.actionCut.setText(QtWidgets.QApplication.translate("MainWindow", "Cu&t", None, -1))
        self.actionCut.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+X", None, -1))
        self.actionCopy.setText(QtWidgets.QApplication.translate("MainWindow", "&Copy", None, -1))
        self.actionCopy.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+C", None, -1))
        self.actionPaste.setText(QtWidgets.QApplication.translate("MainWindow", "&Paste", None, -1))
        self.actionPaste.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+V", None, -1))
        self.actionSelect_All.setText(QtWidgets.QApplication.translate("MainWindow", "Select &All", None, -1))
        self.actionSelect_All.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+A", None, -1))
        self.actionShow_Messages.setText(QtWidgets.QApplication.translate("MainWindow", "Show M&essages", None, -1))
        self.actionStepOver.setText(QtWidgets.QApplication.translate("MainWindow", "Step &Over", None, -1))
        self.actionStepOver.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Step Over", None, -1))
        self.actionStepOver.setShortcut(QtWidgets.QApplication.translate("MainWindow", "F6", None, -1))
        self.actionRestart.setText(QtWidgets.QApplication.translate("MainWindow", "Re&start", None, -1))
        self.actionRestart.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Restart Simulation", None, -1))
        self.actionRestart.setShortcut(QtWidgets.QApplication.translate("MainWindow", "F4", None, -1))
        self.actionShow_Memory_Dump.setText(QtWidgets.QApplication.translate("MainWindow", "Show Memory &Dump", None, -1))
        self.actionShow_LCD_Display.setText(QtWidgets.QApplication.translate("MainWindow", "Show &LCD Display", None, -1))
        self.actionShow_Terminal.setText(QtWidgets.QApplication.translate("MainWindow", "Show Term&inal", None, -1))
        self.actionadd.setText(QtWidgets.QApplication.translate("MainWindow", "add", None, -1))
        self.actionadd_2.setText(QtWidgets.QApplication.translate("MainWindow", "add", None, -1))

from ..widget.myqtreeview import MyQTreeView
from ..widget.memorylcdview import MemoryLCDView
