# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './qtarmsim/ui/preferences.ui',
# licensing of './qtarmsim/ui/preferences.ui' applies.
#
# Created: Tue May  5 11:22:14 2020
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_PreferencesDialog(object):
    def setupUi(self, PreferencesDialog):
        PreferencesDialog.setObjectName("PreferencesDialog")
        PreferencesDialog.setWindowModality(QtCore.Qt.WindowModal)
        PreferencesDialog.resize(660, 498)
        self.verticalLayout = QtWidgets.QVBoxLayout(PreferencesDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(PreferencesDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tabARMSim = QtWidgets.QWidget()
        self.tabARMSim.setObjectName("tabARMSim")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabARMSim)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.tabARMSim)
        self.groupBox.setTitle("ARMSim")
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.labelARMSimCommand = QtWidgets.QLabel(self.groupBox)
        self.labelARMSimCommand.setObjectName("labelARMSimCommand")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelARMSimCommand)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditARMSimDirectory = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditARMSimDirectory.setText("")
        self.lineEditARMSimDirectory.setObjectName("lineEditARMSimDirectory")
        self.horizontalLayout.addWidget(self.lineEditARMSimDirectory)
        self.toolButtonARMSimDirectory = QtWidgets.QToolButton(self.groupBox)
        self.toolButtonARMSimDirectory.setObjectName("toolButtonARMSimDirectory")
        self.horizontalLayout.addWidget(self.toolButtonARMSimDirectory)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEditARMSimCommand = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditARMSimCommand.setObjectName("lineEditARMSimCommand")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditARMSimCommand)
        self.labelARMSimServer = QtWidgets.QLabel(self.groupBox)
        self.labelARMSimServer.setObjectName("labelARMSimServer")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelARMSimServer)
        self.lineEditARMSimServer = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditARMSimServer.setText("")
        self.lineEditARMSimServer.setObjectName("lineEditARMSimServer")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditARMSimServer)
        self.labelARMSimPort = QtWidgets.QLabel(self.groupBox)
        self.labelARMSimPort.setObjectName("labelARMSimPort")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelARMSimPort)
        self.spinBoxARMSimPort = QtWidgets.QSpinBox(self.groupBox)
        self.spinBoxARMSimPort.setMinimum(8000)
        self.spinBoxARMSimPort.setMaximum(9999)
        self.spinBoxARMSimPort.setProperty("value", 8010)
        self.spinBoxARMSimPort.setObjectName("spinBoxARMSimPort")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBoxARMSimPort)
        self.useLabelsLabel = QtWidgets.QLabel(self.groupBox)
        self.useLabelsLabel.setObjectName("useLabelsLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.useLabelsLabel)
        self.useLabelsCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.useLabelsCheckBox.setObjectName("useLabelsCheckBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.useLabelsCheckBox)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabARMSim)
        self.groupBox_2.setTitle("Gcc ARM")
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.lineEditARMGccOptions = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditARMGccOptions.setText("")
        self.lineEditARMGccOptions.setObjectName("lineEditARMGccOptions")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditARMGccOptions)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditARMGccCommand = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditARMGccCommand.setText("")
        self.lineEditARMGccCommand.setObjectName("lineEditARMGccCommand")
        self.horizontalLayout_2.addWidget(self.lineEditARMGccCommand)
        self.toolButtonARMGccCommand = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButtonARMGccCommand.setObjectName("toolButtonARMGccCommand")
        self.horizontalLayout_2.addWidget(self.toolButtonARMGccCommand)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.labelARMGccOptions = QtWidgets.QLabel(self.groupBox_2)
        self.labelARMGccOptions.setObjectName("labelARMGccOptions")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelARMGccOptions)
        self.labelARMGccCommand = QtWidgets.QLabel(self.groupBox_2)
        self.labelARMGccCommand.setObjectName("labelARMGccCommand")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelARMGccCommand)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(20, 43, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButtonARMSimRestoreDefaults = QtWidgets.QPushButton(self.tabARMSim)
        self.pushButtonARMSimRestoreDefaults.setObjectName("pushButtonARMSimRestoreDefaults")
        self.horizontalLayout_3.addWidget(self.pushButtonARMSimRestoreDefaults)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tabARMSim, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(PreferencesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(PreferencesDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), PreferencesDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), PreferencesDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PreferencesDialog)
        PreferencesDialog.setTabOrder(self.lineEditARMSimServer, self.spinBoxARMSimPort)
        PreferencesDialog.setTabOrder(self.spinBoxARMSimPort, self.lineEditARMSimCommand)
        PreferencesDialog.setTabOrder(self.lineEditARMSimCommand, self.lineEditARMSimDirectory)
        PreferencesDialog.setTabOrder(self.lineEditARMSimDirectory, self.toolButtonARMSimDirectory)
        PreferencesDialog.setTabOrder(self.toolButtonARMSimDirectory, self.useLabelsCheckBox)
        PreferencesDialog.setTabOrder(self.useLabelsCheckBox, self.lineEditARMGccCommand)
        PreferencesDialog.setTabOrder(self.lineEditARMGccCommand, self.toolButtonARMGccCommand)
        PreferencesDialog.setTabOrder(self.toolButtonARMGccCommand, self.lineEditARMGccOptions)
        PreferencesDialog.setTabOrder(self.lineEditARMGccOptions, self.pushButtonARMSimRestoreDefaults)
        PreferencesDialog.setTabOrder(self.pushButtonARMSimRestoreDefaults, self.tabWidget)

    def retranslateUi(self, PreferencesDialog):
        PreferencesDialog.setWindowTitle(QtWidgets.QApplication.translate("PreferencesDialog", "QtARMSim Preferences", None, -1))
        self.labelARMSimCommand.setText(QtWidgets.QApplication.translate("PreferencesDialog", "ARMSim directory", None, -1))
        self.toolButtonARMSimDirectory.setText(QtWidgets.QApplication.translate("PreferencesDialog", "...", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("PreferencesDialog", "Command line", None, -1))
        self.labelARMSimServer.setText(QtWidgets.QApplication.translate("PreferencesDialog", "Server", None, -1))
        self.labelARMSimPort.setText(QtWidgets.QApplication.translate("PreferencesDialog", "Port", None, -1))
        self.useLabelsLabel.setText(QtWidgets.QApplication.translate("PreferencesDialog", "Use labels", None, -1))
        self.useLabelsCheckBox.setToolTip(QtWidgets.QApplication.translate("PreferencesDialog", "Use labels on the disassembled code instead of the corresponding numeric value", None, -1))
        self.toolButtonARMGccCommand.setText(QtWidgets.QApplication.translate("PreferencesDialog", "...", None, -1))
        self.labelARMGccOptions.setText(QtWidgets.QApplication.translate("PreferencesDialog", "Options", None, -1))
        self.labelARMGccCommand.setText(QtWidgets.QApplication.translate("PreferencesDialog", "Command line", None, -1))
        self.pushButtonARMSimRestoreDefaults.setText(QtWidgets.QApplication.translate("PreferencesDialog", "Restore Defaults", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabARMSim), QtWidgets.QApplication.translate("PreferencesDialog", "ARMSim", None, -1))

