
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-06T08:10:26+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "cbb55250c38ba18357fd4e0ff01fce2245feee4f",
 "version": "0.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
