
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "41a7f78bba0c7a9f76f0b67f9ddd92d3a367555d",
 "version": "2299"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
