/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CXContactTracingV1"
 * 	found in "../asn1/cx.asn1"
 * 	`asn1c -fincludes-quoted`
 */

#ifndef	_SeedValues_H_
#define	_SeedValues_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SeedValues */
typedef OCTET_STRING_t	 SeedValues_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SeedValues;
asn_struct_free_f SeedValues_free;
asn_struct_print_f SeedValues_print;
asn_constr_check_f SeedValues_constraint;
ber_type_decoder_f SeedValues_decode_ber;
der_type_encoder_f SeedValues_encode_der;
xer_type_decoder_f SeedValues_decode_xer;
xer_type_encoder_f SeedValues_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SeedValues_H_ */
#include "asn_internal.h"
