/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CXContactTracingV1"
 * 	found in "../asn1/cx.asn1"
 * 	`asn1c -fincludes-quoted`
 */

#include "SeedDescriptor.h"

static asn_TYPE_member_t asn_MBR_SeedDescriptor_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SeedDescriptor, generatorType),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_GeneratorType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"generatorType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SeedDescriptor, preseedValue),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"preseedValue"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SeedDescriptor, preseedVerificationKey),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SubjectPublicKeyInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"preseedVerificationKey"
		},
};
static const ber_tlv_tag_t asn_DEF_SeedDescriptor_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SeedDescriptor_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* generatorType */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 0 }, /* preseedValue */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 0 } /* preseedVerificationKey */
};
static asn_SEQUENCE_specifics_t asn_SPC_SeedDescriptor_specs_1 = {
	sizeof(struct SeedDescriptor),
	offsetof(struct SeedDescriptor, _asn_ctx),
	asn_MAP_SeedDescriptor_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SeedDescriptor = {
	"SeedDescriptor",
	"SeedDescriptor",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SeedDescriptor_tags_1,
	sizeof(asn_DEF_SeedDescriptor_tags_1)
		/sizeof(asn_DEF_SeedDescriptor_tags_1[0]), /* 1 */
	asn_DEF_SeedDescriptor_tags_1,	/* Same as above */
	sizeof(asn_DEF_SeedDescriptor_tags_1)
		/sizeof(asn_DEF_SeedDescriptor_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SeedDescriptor_1,
	3,	/* Elements count */
	&asn_SPC_SeedDescriptor_specs_1	/* Additional specs */
};

