/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CXContactTracingV1"
 * 	found in "../asn1/cx.asn1"
 * 	`asn1c -fincludes-quoted`
 */

#include "TBSPublicationData.h"

static asn_TYPE_member_t asn_MBR_TBSPublicationData_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TBSPublicationData, version),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_PublicationVersion,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TBSPublicationData, zone),
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"zone"
		},
	{ ATF_POINTER, 1, offsetof(struct TBSPublicationData, aggregated),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"aggregated"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TBSPublicationData, publishedAt),
		(ASN_TAG_CLASS_UNIVERSAL | (24 << 2)),
		0,
		&asn_DEF_GeneralizedTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"publishedAt"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TBSPublicationData, nextUpdateNotBefore),
		(ASN_TAG_CLASS_UNIVERSAL | (24 << 2)),
		0,
		&asn_DEF_GeneralizedTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"nextUpdateNotBefore"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TBSPublicationData, nextUpdateNotAfter),
		(ASN_TAG_CLASS_UNIVERSAL | (24 << 2)),
		0,
		&asn_DEF_GeneralizedTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"nextUpdateNotAfter"
		},
	{ ATF_POINTER, 1, offsetof(struct TBSPublicationData, excludesPublishedBefore),
		(ASN_TAG_CLASS_UNIVERSAL | (24 << 2)),
		0,
		&asn_DEF_GeneralizedTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"excludesPublishedBefore"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TBSPublicationData, notifications),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Notifications,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"notifications"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TBSPublicationData, updateURLs),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_UpdateURLs,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"updateURLs"
		},
	{ ATF_POINTER, 1, offsetof(struct TBSPublicationData, extensions),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Extensions,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"extensions"
		},
};
static const ber_tlv_tag_t asn_DEF_TBSPublicationData_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TBSPublicationData_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 2, 0, 0 }, /* aggregated */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* version */
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 1, 0, 0 }, /* zone */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 7, 0, 1 }, /* notifications */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 8, -1, 0 }, /* updateURLs */
    { (ASN_TAG_CLASS_UNIVERSAL | (24 << 2)), 3, 0, 3 }, /* publishedAt */
    { (ASN_TAG_CLASS_UNIVERSAL | (24 << 2)), 4, -1, 2 }, /* nextUpdateNotBefore */
    { (ASN_TAG_CLASS_UNIVERSAL | (24 << 2)), 5, -2, 1 }, /* nextUpdateNotAfter */
    { (ASN_TAG_CLASS_UNIVERSAL | (24 << 2)), 6, -3, 0 }, /* excludesPublishedBefore */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 9, 0, 0 } /* extensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_TBSPublicationData_specs_1 = {
	sizeof(struct TBSPublicationData),
	offsetof(struct TBSPublicationData, _asn_ctx),
	asn_MAP_TBSPublicationData_tag2el_1,
	10,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_TBSPublicationData = {
	"TBSPublicationData",
	"TBSPublicationData",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_TBSPublicationData_tags_1,
	sizeof(asn_DEF_TBSPublicationData_tags_1)
		/sizeof(asn_DEF_TBSPublicationData_tags_1[0]), /* 1 */
	asn_DEF_TBSPublicationData_tags_1,	/* Same as above */
	sizeof(asn_DEF_TBSPublicationData_tags_1)
		/sizeof(asn_DEF_TBSPublicationData_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_TBSPublicationData_1,
	10,	/* Elements count */
	&asn_SPC_TBSPublicationData_specs_1	/* Additional specs */
};

