
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-30T17:18:07+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "392e8108e8e5d018b4e8590cd4067fddd4f2ffd3",
 "version": "1.3.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
