= twc(1)
:doctype: manpage
:author: Michał Góral
:email: dev@goral.net.pl
:revnumber: @VERSION@
:man manual: TWC Manual
:man source: TWC {revnumber}
:experimental:

== NAME

TWC - TaskWarrior Controller - interactive command-line task and todo manager.

== SYNOPSIS

*twc* [_OPTIONS_]

== DESCRIPTION

TWC is an interactive command-line task and todo manager which acts as a
frontend for a popular program TaskWarrior. It eases and speeds up the burden
of managing lists of tasks and offers many features which are expected from
modern task and todo managers.

include::manual/program-options.adoc[tags=manpage]

== CONFIGURATION

include::manual/config.adoc[tags=manpage]

== SEE ALSO

*task*(1)

== COPYRIGHT

Copyright (C) 2019 {author}.

TWC is free software: you can redistribute it and/or modify it under the terms
of the GNU General Public License as published by the Free Software Foundation,
either version 3 of the License, or (at your option) any later version.

TWC is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
TWC. If not, see http://www.gnu.org/licenses/.

== BUGS AND ISSUES

Please report any bugs at https://gitlab.com/mgoral/twc/issues.
