
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-28T14:25:51+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "693a4cdcdd5564796917d7b53132557cc8469e02",
 "version": "0.0.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
