
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-27T14:00:06-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2a4995b25614c2fa20b2eaae94f6a1f91b1a8499",
 "version": "v0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
