RETHINK_HOST = 'RETHINK_HOST'
RETHINK_PORT = 'RETHINK_PORT'
RETHINK_DB = 'RETHINK_DB'
RETHINK_USERNAME = 'RETHINK_USERNAME'
RETHINK_PASSWORD = 'RETHINK_PASSWORD'
RETHINK_CERT_PATH = 'RETHINK_CERT_PATH'

TRANSACTION_DATA = 'transaction_data'
USAGE_ACTIVITY_DATA = 'usage_activity_data'
ERROR = 'error'
NODE_DEFINITIONS = 'node_definitions'

CACERT = 'cacert.pem'