
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-28T17:13:09+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "22c49c5c468ad2239d6c4ca5ec8dfab406be68a0",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
