
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-06T18:33:57+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ed3c7ce22b9a983bd133d8b1b46d909afadeaa6f",
 "version": "0.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
