
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-05T16:44:18+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0975a571c0a0b8cb5847e2655f54d035a0fe2a22",
 "version": "0.0.32"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
