name = 'pyglobal'
version = '0.0.1'
description = 'Global accessors for things like settings. This could be used across applications and modules to share data.'
url = 'https://github.com/justengel/pyglobal'
author = 'Justin Engel'
author_email = 'jtengel08@gmail.com'
