entry = {'author': None,
 'comments': 'http://eztv.it/forum/discuss/57203/',
 'contentlength': '1064571425',
 'filename': 'Under.the.Dome.S02E05.720p.HDTV.X264-DIMENSION.[eztv].torrent',
 'guidislink': False,
 'id': 'http://eztv.it/ep/57203/under-the-dome-s02e05-720p-hdtv-x264-dimension/',
 'infohash': '4985B6451A38BFEAB22681A9F853B4FC8EC3B62F',
 'link': 'http://re.zoink.it/4998089485',
 'links': [{'href': 'http://re.zoink.it/4998089485',
            'rel': 'alternate',
            'type': 'text/html'},
           {'href': 'http://re.zoink.it/4998089485',
            'length': '1064571425',
            'rel': 'enclosure',
            'type': 'application/x-bittorrent'}],
 'magneturi': 'magnet:?xt=urn:btih:JGC3MRI2HC76VMRGQGU7QU5U7SHMHNRP&dn=Under.the.Dome.S02E05.720p.HDTV.X264-DIMENSION',
 'published': 'Tue, 29 Jul 2014 02:09:53 -0500',
 'published_parsed': None,
 'summary': 'Show Name: Under the Dome; Episode Title: N/A; Season: 2; '
            'Episode: 5',
 'summary_detail': {'base': 'https://ezrss.it/feed/',
                    'language': None,
                    'type': 'text/html',
                    'value': 'Show Name: Under the Dome; Episode Title: '
                             'N/A; Season: 2; Episode: 5'},
 'tags': None,
 'title': 'Under the Dome 2x5 [720P - HDTV - DIMENSION]',
 'title_detail': {'base': 'https://ezrss.it/feed/',
                  'language': None,
                  'type': 'text/plain',
                  'value': 'Under the Dome 2x5 [720P - HDTV - DIMENSION]'},
 'torrent': ''}