# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _itkGaussianSpatialObjectPython.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_itkGaussianSpatialObjectPython', [dirname(__file__)])
        except ImportError:
            import _itkGaussianSpatialObjectPython
            return _itkGaussianSpatialObjectPython
        if fp is not None:
            try:
                _mod = imp.load_module('_itkGaussianSpatialObjectPython', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _itkGaussianSpatialObjectPython = swig_import_helper()
    del swig_import_helper
else:
    import _itkGaussianSpatialObjectPython
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


import itkEllipseSpatialObjectPython
import itkFixedArrayPython
import pyBasePython
import ITKCommonBasePython
import itkSpatialObjectBasePython
import itkBoundingBoxPython
import itkVectorContainerPython
import itkVectorPython
import vnl_vectorPython
import stdcomplexPython
import vnl_matrixPython
import vnl_vector_refPython
import itkOffsetPython
import itkSizePython
import itkMatrixPython
import vnl_matrix_fixedPython
import itkCovariantVectorPython
import itkPointPython
import itkContinuousIndexPython
import itkIndexPython
import itkMapContainerPython
import itkAffineTransformPython
import itkTransformBasePython
import itkDiffusionTensor3DPython
import itkSymmetricSecondRankTensorPython
import itkVariableLengthVectorPython
import itkOptimizerParametersPython
import itkArrayPython
import itkArray2DPython
import itkMatrixOffsetTransformBasePython
import itkSpatialObjectPropertyPython
import itkRGBAPixelPython
import itkImageRegionPython

def itkGaussianSpatialObject3_New():
  return itkGaussianSpatialObject3.New()


def itkGaussianSpatialObject2_New():
  return itkGaussianSpatialObject2.New()

class listitkGaussianSpatialObject2_Pointer(object):
    """Proxy of C++ std::list<(itkGaussianSpatialObject2_Pointer)> class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self) -> "swig::SwigPyIterator *":
        """iterator(listitkGaussianSpatialObject2_Pointer self) -> SwigPyIterator"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_iterator(self)

    def __iter__(self):
        return self.iterator()

    def __nonzero__(self) -> "bool":
        """__nonzero__(listitkGaussianSpatialObject2_Pointer self) -> bool"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer___nonzero__(self)


    def __bool__(self) -> "bool":
        """__bool__(listitkGaussianSpatialObject2_Pointer self) -> bool"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer___bool__(self)


    def __len__(self) -> "std::list< itkGaussianSpatialObject2_Pointer >::size_type":
        """__len__(listitkGaussianSpatialObject2_Pointer self) -> std::list< itkGaussianSpatialObject2_Pointer >::size_type"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer___len__(self)


    def __getslice__(self, i: 'std::list< itkGaussianSpatialObject2_Pointer >::difference_type', j: 'std::list< itkGaussianSpatialObject2_Pointer >::difference_type') -> "std::list< itkGaussianSpatialObject2_Pointer,std::allocator< itkGaussianSpatialObject2_Pointer > > *":
        """__getslice__(listitkGaussianSpatialObject2_Pointer self, std::list< itkGaussianSpatialObject2_Pointer >::difference_type i, std::list< itkGaussianSpatialObject2_Pointer >::difference_type j) -> listitkGaussianSpatialObject2_Pointer"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer___getslice__(self, i, j)


    def __setslice__(self, *args) -> "void":
        """
        __setslice__(listitkGaussianSpatialObject2_Pointer self, std::list< itkGaussianSpatialObject2_Pointer >::difference_type i, std::list< itkGaussianSpatialObject2_Pointer >::difference_type j)
        __setslice__(listitkGaussianSpatialObject2_Pointer self, std::list< itkGaussianSpatialObject2_Pointer >::difference_type i, std::list< itkGaussianSpatialObject2_Pointer >::difference_type j, listitkGaussianSpatialObject2_Pointer v)
        """
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer___setslice__(self, *args)


    def __delslice__(self, i: 'std::list< itkGaussianSpatialObject2_Pointer >::difference_type', j: 'std::list< itkGaussianSpatialObject2_Pointer >::difference_type') -> "void":
        """__delslice__(listitkGaussianSpatialObject2_Pointer self, std::list< itkGaussianSpatialObject2_Pointer >::difference_type i, std::list< itkGaussianSpatialObject2_Pointer >::difference_type j)"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer___delslice__(self, i, j)


    def __delitem__(self, *args) -> "void":
        """
        __delitem__(listitkGaussianSpatialObject2_Pointer self, std::list< itkGaussianSpatialObject2_Pointer >::difference_type i)
        __delitem__(listitkGaussianSpatialObject2_Pointer self, PySliceObject * slice)
        """
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer___delitem__(self, *args)


    def __getitem__(self, *args) -> "std::list< itkGaussianSpatialObject2_Pointer >::value_type const &":
        """
        __getitem__(listitkGaussianSpatialObject2_Pointer self, PySliceObject * slice) -> listitkGaussianSpatialObject2_Pointer
        __getitem__(listitkGaussianSpatialObject2_Pointer self, std::list< itkGaussianSpatialObject2_Pointer >::difference_type i) -> std::list< itkGaussianSpatialObject2_Pointer >::value_type const &
        """
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer___getitem__(self, *args)


    def __setitem__(self, *args) -> "void":
        """
        __setitem__(listitkGaussianSpatialObject2_Pointer self, PySliceObject * slice, listitkGaussianSpatialObject2_Pointer v)
        __setitem__(listitkGaussianSpatialObject2_Pointer self, PySliceObject * slice)
        __setitem__(listitkGaussianSpatialObject2_Pointer self, std::list< itkGaussianSpatialObject2_Pointer >::difference_type i, std::list< itkGaussianSpatialObject2_Pointer >::value_type const & x)
        """
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer___setitem__(self, *args)


    def pop(self) -> "std::list< itkGaussianSpatialObject2_Pointer >::value_type":
        """pop(listitkGaussianSpatialObject2_Pointer self) -> std::list< itkGaussianSpatialObject2_Pointer >::value_type"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_pop(self)


    def append(self, x: 'std::list< itkGaussianSpatialObject2_Pointer >::value_type const &') -> "void":
        """append(listitkGaussianSpatialObject2_Pointer self, std::list< itkGaussianSpatialObject2_Pointer >::value_type const & x)"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_append(self, x)


    def empty(self) -> "bool":
        """empty(listitkGaussianSpatialObject2_Pointer self) -> bool"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_empty(self)


    def size(self) -> "std::list< itkGaussianSpatialObject2_Pointer >::size_type":
        """size(listitkGaussianSpatialObject2_Pointer self) -> std::list< itkGaussianSpatialObject2_Pointer >::size_type"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_size(self)


    def swap(self, v: 'listitkGaussianSpatialObject2_Pointer') -> "void":
        """swap(listitkGaussianSpatialObject2_Pointer self, listitkGaussianSpatialObject2_Pointer v)"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_swap(self, v)


    def begin(self) -> "std::list< itkGaussianSpatialObject2_Pointer >::iterator":
        """begin(listitkGaussianSpatialObject2_Pointer self) -> std::list< itkGaussianSpatialObject2_Pointer >::iterator"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_begin(self)


    def end(self) -> "std::list< itkGaussianSpatialObject2_Pointer >::iterator":
        """end(listitkGaussianSpatialObject2_Pointer self) -> std::list< itkGaussianSpatialObject2_Pointer >::iterator"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_end(self)


    def rbegin(self) -> "std::list< itkGaussianSpatialObject2_Pointer >::reverse_iterator":
        """rbegin(listitkGaussianSpatialObject2_Pointer self) -> std::list< itkGaussianSpatialObject2_Pointer >::reverse_iterator"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_rbegin(self)


    def rend(self) -> "std::list< itkGaussianSpatialObject2_Pointer >::reverse_iterator":
        """rend(listitkGaussianSpatialObject2_Pointer self) -> std::list< itkGaussianSpatialObject2_Pointer >::reverse_iterator"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_rend(self)


    def clear(self) -> "void":
        """clear(listitkGaussianSpatialObject2_Pointer self)"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_clear(self)


    def get_allocator(self) -> "std::list< itkGaussianSpatialObject2_Pointer >::allocator_type":
        """get_allocator(listitkGaussianSpatialObject2_Pointer self) -> std::list< itkGaussianSpatialObject2_Pointer >::allocator_type"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_get_allocator(self)


    def pop_back(self) -> "void":
        """pop_back(listitkGaussianSpatialObject2_Pointer self)"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_pop_back(self)


    def erase(self, *args) -> "std::list< itkGaussianSpatialObject2_Pointer >::iterator":
        """
        erase(listitkGaussianSpatialObject2_Pointer self, std::list< itkGaussianSpatialObject2_Pointer >::iterator pos) -> std::list< itkGaussianSpatialObject2_Pointer >::iterator
        erase(listitkGaussianSpatialObject2_Pointer self, std::list< itkGaussianSpatialObject2_Pointer >::iterator first, std::list< itkGaussianSpatialObject2_Pointer >::iterator last) -> std::list< itkGaussianSpatialObject2_Pointer >::iterator
        """
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_erase(self, *args)


    def __init__(self, *args):
        """
        __init__(std::list<(itkGaussianSpatialObject2_Pointer)> self) -> listitkGaussianSpatialObject2_Pointer
        __init__(std::list<(itkGaussianSpatialObject2_Pointer)> self, listitkGaussianSpatialObject2_Pointer arg2) -> listitkGaussianSpatialObject2_Pointer
        __init__(std::list<(itkGaussianSpatialObject2_Pointer)> self, std::list< itkGaussianSpatialObject2_Pointer >::size_type size) -> listitkGaussianSpatialObject2_Pointer
        __init__(std::list<(itkGaussianSpatialObject2_Pointer)> self, std::list< itkGaussianSpatialObject2_Pointer >::size_type size, std::list< itkGaussianSpatialObject2_Pointer >::value_type const & value) -> listitkGaussianSpatialObject2_Pointer
        """
        _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_swiginit(self, _itkGaussianSpatialObjectPython.new_listitkGaussianSpatialObject2_Pointer(*args))

    def push_back(self, x: 'std::list< itkGaussianSpatialObject2_Pointer >::value_type const &') -> "void":
        """push_back(listitkGaussianSpatialObject2_Pointer self, std::list< itkGaussianSpatialObject2_Pointer >::value_type const & x)"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_push_back(self, x)


    def front(self) -> "std::list< itkGaussianSpatialObject2_Pointer >::value_type const &":
        """front(listitkGaussianSpatialObject2_Pointer self) -> std::list< itkGaussianSpatialObject2_Pointer >::value_type const &"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_front(self)


    def back(self) -> "std::list< itkGaussianSpatialObject2_Pointer >::value_type const &":
        """back(listitkGaussianSpatialObject2_Pointer self) -> std::list< itkGaussianSpatialObject2_Pointer >::value_type const &"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_back(self)


    def assign(self, n: 'std::list< itkGaussianSpatialObject2_Pointer >::size_type', x: 'std::list< itkGaussianSpatialObject2_Pointer >::value_type const &') -> "void":
        """assign(listitkGaussianSpatialObject2_Pointer self, std::list< itkGaussianSpatialObject2_Pointer >::size_type n, std::list< itkGaussianSpatialObject2_Pointer >::value_type const & x)"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_assign(self, n, x)


    def resize(self, *args) -> "void":
        """
        resize(listitkGaussianSpatialObject2_Pointer self, std::list< itkGaussianSpatialObject2_Pointer >::size_type new_size)
        resize(listitkGaussianSpatialObject2_Pointer self, std::list< itkGaussianSpatialObject2_Pointer >::size_type new_size, std::list< itkGaussianSpatialObject2_Pointer >::value_type const & x)
        """
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_resize(self, *args)


    def insert(self, *args) -> "void":
        """
        insert(listitkGaussianSpatialObject2_Pointer self, std::list< itkGaussianSpatialObject2_Pointer >::iterator pos, std::list< itkGaussianSpatialObject2_Pointer >::value_type const & x) -> std::list< itkGaussianSpatialObject2_Pointer >::iterator
        insert(listitkGaussianSpatialObject2_Pointer self, std::list< itkGaussianSpatialObject2_Pointer >::iterator pos, std::list< itkGaussianSpatialObject2_Pointer >::size_type n, std::list< itkGaussianSpatialObject2_Pointer >::value_type const & x)
        """
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_insert(self, *args)


    def pop_front(self) -> "void":
        """pop_front(listitkGaussianSpatialObject2_Pointer self)"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_pop_front(self)


    def push_front(self, x: 'std::list< itkGaussianSpatialObject2_Pointer >::value_type const &') -> "void":
        """push_front(listitkGaussianSpatialObject2_Pointer self, std::list< itkGaussianSpatialObject2_Pointer >::value_type const & x)"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_push_front(self, x)


    def reverse(self) -> "void":
        """reverse(listitkGaussianSpatialObject2_Pointer self)"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_reverse(self)

    __swig_destroy__ = _itkGaussianSpatialObjectPython.delete_listitkGaussianSpatialObject2_Pointer
listitkGaussianSpatialObject2_Pointer.iterator = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_iterator, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.__nonzero__ = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer___nonzero__, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.__bool__ = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer___bool__, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.__len__ = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer___len__, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.__getslice__ = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer___getslice__, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.__setslice__ = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer___setslice__, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.__delslice__ = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer___delslice__, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.__delitem__ = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer___delitem__, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.__getitem__ = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer___getitem__, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.__setitem__ = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer___setitem__, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.pop = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_pop, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.append = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_append, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.empty = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_empty, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.size = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_size, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.swap = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_swap, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.begin = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_begin, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.end = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_end, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.rbegin = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_rbegin, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.rend = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_rend, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.clear = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_clear, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.get_allocator = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_get_allocator, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.pop_back = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_pop_back, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.erase = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_erase, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.push_back = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_push_back, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.front = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_front, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.back = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_back, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.assign = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_assign, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.resize = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_resize, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.insert = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_insert, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.pop_front = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_pop_front, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.push_front = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_push_front, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer.reverse = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_reverse, None, listitkGaussianSpatialObject2_Pointer)
listitkGaussianSpatialObject2_Pointer_swigregister = _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject2_Pointer_swigregister
listitkGaussianSpatialObject2_Pointer_swigregister(listitkGaussianSpatialObject2_Pointer)

class listitkGaussianSpatialObject3_Pointer(object):
    """Proxy of C++ std::list<(itkGaussianSpatialObject3_Pointer)> class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self) -> "swig::SwigPyIterator *":
        """iterator(listitkGaussianSpatialObject3_Pointer self) -> SwigPyIterator"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_iterator(self)

    def __iter__(self):
        return self.iterator()

    def __nonzero__(self) -> "bool":
        """__nonzero__(listitkGaussianSpatialObject3_Pointer self) -> bool"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer___nonzero__(self)


    def __bool__(self) -> "bool":
        """__bool__(listitkGaussianSpatialObject3_Pointer self) -> bool"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer___bool__(self)


    def __len__(self) -> "std::list< itkGaussianSpatialObject3_Pointer >::size_type":
        """__len__(listitkGaussianSpatialObject3_Pointer self) -> std::list< itkGaussianSpatialObject3_Pointer >::size_type"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer___len__(self)


    def __getslice__(self, i: 'std::list< itkGaussianSpatialObject3_Pointer >::difference_type', j: 'std::list< itkGaussianSpatialObject3_Pointer >::difference_type') -> "std::list< itkGaussianSpatialObject3_Pointer,std::allocator< itkGaussianSpatialObject3_Pointer > > *":
        """__getslice__(listitkGaussianSpatialObject3_Pointer self, std::list< itkGaussianSpatialObject3_Pointer >::difference_type i, std::list< itkGaussianSpatialObject3_Pointer >::difference_type j) -> listitkGaussianSpatialObject3_Pointer"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer___getslice__(self, i, j)


    def __setslice__(self, *args) -> "void":
        """
        __setslice__(listitkGaussianSpatialObject3_Pointer self, std::list< itkGaussianSpatialObject3_Pointer >::difference_type i, std::list< itkGaussianSpatialObject3_Pointer >::difference_type j)
        __setslice__(listitkGaussianSpatialObject3_Pointer self, std::list< itkGaussianSpatialObject3_Pointer >::difference_type i, std::list< itkGaussianSpatialObject3_Pointer >::difference_type j, listitkGaussianSpatialObject3_Pointer v)
        """
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer___setslice__(self, *args)


    def __delslice__(self, i: 'std::list< itkGaussianSpatialObject3_Pointer >::difference_type', j: 'std::list< itkGaussianSpatialObject3_Pointer >::difference_type') -> "void":
        """__delslice__(listitkGaussianSpatialObject3_Pointer self, std::list< itkGaussianSpatialObject3_Pointer >::difference_type i, std::list< itkGaussianSpatialObject3_Pointer >::difference_type j)"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer___delslice__(self, i, j)


    def __delitem__(self, *args) -> "void":
        """
        __delitem__(listitkGaussianSpatialObject3_Pointer self, std::list< itkGaussianSpatialObject3_Pointer >::difference_type i)
        __delitem__(listitkGaussianSpatialObject3_Pointer self, PySliceObject * slice)
        """
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer___delitem__(self, *args)


    def __getitem__(self, *args) -> "std::list< itkGaussianSpatialObject3_Pointer >::value_type const &":
        """
        __getitem__(listitkGaussianSpatialObject3_Pointer self, PySliceObject * slice) -> listitkGaussianSpatialObject3_Pointer
        __getitem__(listitkGaussianSpatialObject3_Pointer self, std::list< itkGaussianSpatialObject3_Pointer >::difference_type i) -> std::list< itkGaussianSpatialObject3_Pointer >::value_type const &
        """
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer___getitem__(self, *args)


    def __setitem__(self, *args) -> "void":
        """
        __setitem__(listitkGaussianSpatialObject3_Pointer self, PySliceObject * slice, listitkGaussianSpatialObject3_Pointer v)
        __setitem__(listitkGaussianSpatialObject3_Pointer self, PySliceObject * slice)
        __setitem__(listitkGaussianSpatialObject3_Pointer self, std::list< itkGaussianSpatialObject3_Pointer >::difference_type i, std::list< itkGaussianSpatialObject3_Pointer >::value_type const & x)
        """
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer___setitem__(self, *args)


    def pop(self) -> "std::list< itkGaussianSpatialObject3_Pointer >::value_type":
        """pop(listitkGaussianSpatialObject3_Pointer self) -> std::list< itkGaussianSpatialObject3_Pointer >::value_type"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_pop(self)


    def append(self, x: 'std::list< itkGaussianSpatialObject3_Pointer >::value_type const &') -> "void":
        """append(listitkGaussianSpatialObject3_Pointer self, std::list< itkGaussianSpatialObject3_Pointer >::value_type const & x)"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_append(self, x)


    def empty(self) -> "bool":
        """empty(listitkGaussianSpatialObject3_Pointer self) -> bool"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_empty(self)


    def size(self) -> "std::list< itkGaussianSpatialObject3_Pointer >::size_type":
        """size(listitkGaussianSpatialObject3_Pointer self) -> std::list< itkGaussianSpatialObject3_Pointer >::size_type"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_size(self)


    def swap(self, v: 'listitkGaussianSpatialObject3_Pointer') -> "void":
        """swap(listitkGaussianSpatialObject3_Pointer self, listitkGaussianSpatialObject3_Pointer v)"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_swap(self, v)


    def begin(self) -> "std::list< itkGaussianSpatialObject3_Pointer >::iterator":
        """begin(listitkGaussianSpatialObject3_Pointer self) -> std::list< itkGaussianSpatialObject3_Pointer >::iterator"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_begin(self)


    def end(self) -> "std::list< itkGaussianSpatialObject3_Pointer >::iterator":
        """end(listitkGaussianSpatialObject3_Pointer self) -> std::list< itkGaussianSpatialObject3_Pointer >::iterator"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_end(self)


    def rbegin(self) -> "std::list< itkGaussianSpatialObject3_Pointer >::reverse_iterator":
        """rbegin(listitkGaussianSpatialObject3_Pointer self) -> std::list< itkGaussianSpatialObject3_Pointer >::reverse_iterator"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_rbegin(self)


    def rend(self) -> "std::list< itkGaussianSpatialObject3_Pointer >::reverse_iterator":
        """rend(listitkGaussianSpatialObject3_Pointer self) -> std::list< itkGaussianSpatialObject3_Pointer >::reverse_iterator"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_rend(self)


    def clear(self) -> "void":
        """clear(listitkGaussianSpatialObject3_Pointer self)"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_clear(self)


    def get_allocator(self) -> "std::list< itkGaussianSpatialObject3_Pointer >::allocator_type":
        """get_allocator(listitkGaussianSpatialObject3_Pointer self) -> std::list< itkGaussianSpatialObject3_Pointer >::allocator_type"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_get_allocator(self)


    def pop_back(self) -> "void":
        """pop_back(listitkGaussianSpatialObject3_Pointer self)"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_pop_back(self)


    def erase(self, *args) -> "std::list< itkGaussianSpatialObject3_Pointer >::iterator":
        """
        erase(listitkGaussianSpatialObject3_Pointer self, std::list< itkGaussianSpatialObject3_Pointer >::iterator pos) -> std::list< itkGaussianSpatialObject3_Pointer >::iterator
        erase(listitkGaussianSpatialObject3_Pointer self, std::list< itkGaussianSpatialObject3_Pointer >::iterator first, std::list< itkGaussianSpatialObject3_Pointer >::iterator last) -> std::list< itkGaussianSpatialObject3_Pointer >::iterator
        """
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_erase(self, *args)


    def __init__(self, *args):
        """
        __init__(std::list<(itkGaussianSpatialObject3_Pointer)> self) -> listitkGaussianSpatialObject3_Pointer
        __init__(std::list<(itkGaussianSpatialObject3_Pointer)> self, listitkGaussianSpatialObject3_Pointer arg2) -> listitkGaussianSpatialObject3_Pointer
        __init__(std::list<(itkGaussianSpatialObject3_Pointer)> self, std::list< itkGaussianSpatialObject3_Pointer >::size_type size) -> listitkGaussianSpatialObject3_Pointer
        __init__(std::list<(itkGaussianSpatialObject3_Pointer)> self, std::list< itkGaussianSpatialObject3_Pointer >::size_type size, std::list< itkGaussianSpatialObject3_Pointer >::value_type const & value) -> listitkGaussianSpatialObject3_Pointer
        """
        _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_swiginit(self, _itkGaussianSpatialObjectPython.new_listitkGaussianSpatialObject3_Pointer(*args))

    def push_back(self, x: 'std::list< itkGaussianSpatialObject3_Pointer >::value_type const &') -> "void":
        """push_back(listitkGaussianSpatialObject3_Pointer self, std::list< itkGaussianSpatialObject3_Pointer >::value_type const & x)"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_push_back(self, x)


    def front(self) -> "std::list< itkGaussianSpatialObject3_Pointer >::value_type const &":
        """front(listitkGaussianSpatialObject3_Pointer self) -> std::list< itkGaussianSpatialObject3_Pointer >::value_type const &"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_front(self)


    def back(self) -> "std::list< itkGaussianSpatialObject3_Pointer >::value_type const &":
        """back(listitkGaussianSpatialObject3_Pointer self) -> std::list< itkGaussianSpatialObject3_Pointer >::value_type const &"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_back(self)


    def assign(self, n: 'std::list< itkGaussianSpatialObject3_Pointer >::size_type', x: 'std::list< itkGaussianSpatialObject3_Pointer >::value_type const &') -> "void":
        """assign(listitkGaussianSpatialObject3_Pointer self, std::list< itkGaussianSpatialObject3_Pointer >::size_type n, std::list< itkGaussianSpatialObject3_Pointer >::value_type const & x)"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_assign(self, n, x)


    def resize(self, *args) -> "void":
        """
        resize(listitkGaussianSpatialObject3_Pointer self, std::list< itkGaussianSpatialObject3_Pointer >::size_type new_size)
        resize(listitkGaussianSpatialObject3_Pointer self, std::list< itkGaussianSpatialObject3_Pointer >::size_type new_size, std::list< itkGaussianSpatialObject3_Pointer >::value_type const & x)
        """
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_resize(self, *args)


    def insert(self, *args) -> "void":
        """
        insert(listitkGaussianSpatialObject3_Pointer self, std::list< itkGaussianSpatialObject3_Pointer >::iterator pos, std::list< itkGaussianSpatialObject3_Pointer >::value_type const & x) -> std::list< itkGaussianSpatialObject3_Pointer >::iterator
        insert(listitkGaussianSpatialObject3_Pointer self, std::list< itkGaussianSpatialObject3_Pointer >::iterator pos, std::list< itkGaussianSpatialObject3_Pointer >::size_type n, std::list< itkGaussianSpatialObject3_Pointer >::value_type const & x)
        """
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_insert(self, *args)


    def pop_front(self) -> "void":
        """pop_front(listitkGaussianSpatialObject3_Pointer self)"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_pop_front(self)


    def push_front(self, x: 'std::list< itkGaussianSpatialObject3_Pointer >::value_type const &') -> "void":
        """push_front(listitkGaussianSpatialObject3_Pointer self, std::list< itkGaussianSpatialObject3_Pointer >::value_type const & x)"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_push_front(self, x)


    def reverse(self) -> "void":
        """reverse(listitkGaussianSpatialObject3_Pointer self)"""
        return _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_reverse(self)

    __swig_destroy__ = _itkGaussianSpatialObjectPython.delete_listitkGaussianSpatialObject3_Pointer
listitkGaussianSpatialObject3_Pointer.iterator = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_iterator, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.__nonzero__ = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer___nonzero__, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.__bool__ = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer___bool__, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.__len__ = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer___len__, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.__getslice__ = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer___getslice__, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.__setslice__ = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer___setslice__, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.__delslice__ = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer___delslice__, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.__delitem__ = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer___delitem__, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.__getitem__ = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer___getitem__, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.__setitem__ = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer___setitem__, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.pop = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_pop, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.append = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_append, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.empty = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_empty, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.size = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_size, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.swap = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_swap, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.begin = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_begin, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.end = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_end, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.rbegin = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_rbegin, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.rend = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_rend, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.clear = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_clear, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.get_allocator = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_get_allocator, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.pop_back = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_pop_back, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.erase = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_erase, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.push_back = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_push_back, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.front = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_front, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.back = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_back, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.assign = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_assign, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.resize = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_resize, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.insert = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_insert, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.pop_front = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_pop_front, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.push_front = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_push_front, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer.reverse = new_instancemethod(_itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_reverse, None, listitkGaussianSpatialObject3_Pointer)
listitkGaussianSpatialObject3_Pointer_swigregister = _itkGaussianSpatialObjectPython.listitkGaussianSpatialObject3_Pointer_swigregister
listitkGaussianSpatialObject3_Pointer_swigregister(listitkGaussianSpatialObject3_Pointer)

class itkGaussianSpatialObject2(itkSpatialObjectBasePython.itkSpatialObject2):
    """


    Represents a multivariate Gaussian function.

    The Gaussian function G(x) is given by \\[ G(\\vec{x}) = m
    e^{-\\|\\S^{-1} \\vec{x}\\|^2 / 2}, \\] where m is a scaling
    factor set by SetMaximum(), and $\\S$ is the (invertible) matrix
    associated to the IndexToObjectTransform of the object multiplied by
    the Sigma parameter. If $\\S$ is symmetric and positive definite,
    and m is chosen so that the integral of G(x) is 1, then G will denote
    a normal distribution with mean 0 and covariance matrix $\\S
    \\times Sigma$.

    C++ includes: itkGaussianSpatialObject.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkGaussianSpatialObject2_Pointer":
        """__New_orig__() -> itkGaussianSpatialObject2_Pointer"""
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkGaussianSpatialObject2_Pointer":
        """Clone(itkGaussianSpatialObject2 self) -> itkGaussianSpatialObject2_Pointer"""
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject2_Clone(self)


    def SetRadiusInObjectSpace(self, _arg: 'double const') -> "void":
        """
        SetRadiusInObjectSpace(itkGaussianSpatialObject2 self, double const _arg)

        The Radius
        determines the bounding box, and which points are considered to be
        inside the SpatialObject. All points with z-score less than the radius
        are in the object. 
        """
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject2_SetRadiusInObjectSpace(self, _arg)


    def GetRadiusInObjectSpace(self) -> "double const &":
        """GetRadiusInObjectSpace(itkGaussianSpatialObject2 self) -> double const &"""
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject2_GetRadiusInObjectSpace(self)


    def SetSigmaInObjectSpace(self, _arg: 'double const') -> "void":
        """
        SetSigmaInObjectSpace(itkGaussianSpatialObject2 self, double const _arg)

        The Sigma
        parameter determines the fallout of the Gaussian inside of the region
        defined by the Radius parameter. 
        """
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject2_SetSigmaInObjectSpace(self, _arg)


    def GetSigmaInObjectSpace(self) -> "double const &":
        """GetSigmaInObjectSpace(itkGaussianSpatialObject2 self) -> double const &"""
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject2_GetSigmaInObjectSpace(self)


    def SetCenterInObjectSpace(self, _arg: 'itkPointD2') -> "void":
        """SetCenterInObjectSpace(itkGaussianSpatialObject2 self, itkPointD2 _arg)"""
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject2_SetCenterInObjectSpace(self, _arg)


    def GetCenterInObjectSpace(self) -> "itkPointD2 const &":
        """GetCenterInObjectSpace(itkGaussianSpatialObject2 self) -> itkPointD2"""
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject2_GetCenterInObjectSpace(self)


    def SetMaximum(self, _arg: 'double const') -> "void":
        """
        SetMaximum(itkGaussianSpatialObject2 self, double const _arg)

        The maximum value of the
        Gaussian (its value at the origin of the spatial object coordinate
        system). 
        """
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject2_SetMaximum(self, _arg)


    def GetMaximum(self) -> "double const &":
        """GetMaximum(itkGaussianSpatialObject2 self) -> double const &"""
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject2_GetMaximum(self)


    def SquaredZScoreInObjectSpace(self, point: 'itkPointD2') -> "double":
        """SquaredZScoreInObjectSpace(itkGaussianSpatialObject2 self, itkPointD2 point) -> double"""
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject2_SquaredZScoreInObjectSpace(self, point)


    def SquaredZScoreInWorldSpace(self, point: 'itkPointD2') -> "double":
        """SquaredZScoreInWorldSpace(itkGaussianSpatialObject2 self, itkPointD2 point) -> double"""
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject2_SquaredZScoreInWorldSpace(self, point)


    def ValueAtInObjectSpace(self, *args) -> "bool":
        """
        ValueAtInObjectSpace(itkGaussianSpatialObject2 self, itkPointD2 point, double & value, unsigned int depth=0, std::string const & name) -> bool
        ValueAtInObjectSpace(itkGaussianSpatialObject2 self, itkPointD2 point, double & value, unsigned int depth=0) -> bool
        ValueAtInObjectSpace(itkGaussianSpatialObject2 self, itkPointD2 point, double & value) -> bool

        Returns the
        value of the Gaussian at the given point. 
        """
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject2_ValueAtInObjectSpace(self, *args)


    def GetEllipsoid(self) -> "itkEllipseSpatialObject2_Pointer":
        """
        GetEllipsoid(itkGaussianSpatialObject2 self) -> itkEllipseSpatialObject2_Pointer

        Returns the
        sigma=m_Radius level set of the Gaussian function, as an
        EllipseSpatialObject. 
        """
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject2_GetEllipsoid(self)

    __swig_destroy__ = _itkGaussianSpatialObjectPython.delete_itkGaussianSpatialObject2

    def cast(obj: 'itkLightObject') -> "itkGaussianSpatialObject2 *":
        """cast(itkLightObject obj) -> itkGaussianSpatialObject2"""
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject2_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkGaussianSpatialObject2

        Create a new object of the class itkGaussianSpatialObject2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkGaussianSpatialObject2.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkGaussianSpatialObject2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkGaussianSpatialObject2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkGaussianSpatialObject2.Clone = new_instancemethod(_itkGaussianSpatialObjectPython.itkGaussianSpatialObject2_Clone, None, itkGaussianSpatialObject2)
itkGaussianSpatialObject2.SetRadiusInObjectSpace = new_instancemethod(_itkGaussianSpatialObjectPython.itkGaussianSpatialObject2_SetRadiusInObjectSpace, None, itkGaussianSpatialObject2)
itkGaussianSpatialObject2.GetRadiusInObjectSpace = new_instancemethod(_itkGaussianSpatialObjectPython.itkGaussianSpatialObject2_GetRadiusInObjectSpace, None, itkGaussianSpatialObject2)
itkGaussianSpatialObject2.SetSigmaInObjectSpace = new_instancemethod(_itkGaussianSpatialObjectPython.itkGaussianSpatialObject2_SetSigmaInObjectSpace, None, itkGaussianSpatialObject2)
itkGaussianSpatialObject2.GetSigmaInObjectSpace = new_instancemethod(_itkGaussianSpatialObjectPython.itkGaussianSpatialObject2_GetSigmaInObjectSpace, None, itkGaussianSpatialObject2)
itkGaussianSpatialObject2.SetCenterInObjectSpace = new_instancemethod(_itkGaussianSpatialObjectPython.itkGaussianSpatialObject2_SetCenterInObjectSpace, None, itkGaussianSpatialObject2)
itkGaussianSpatialObject2.GetCenterInObjectSpace = new_instancemethod(_itkGaussianSpatialObjectPython.itkGaussianSpatialObject2_GetCenterInObjectSpace, None, itkGaussianSpatialObject2)
itkGaussianSpatialObject2.SetMaximum = new_instancemethod(_itkGaussianSpatialObjectPython.itkGaussianSpatialObject2_SetMaximum, None, itkGaussianSpatialObject2)
itkGaussianSpatialObject2.GetMaximum = new_instancemethod(_itkGaussianSpatialObjectPython.itkGaussianSpatialObject2_GetMaximum, None, itkGaussianSpatialObject2)
itkGaussianSpatialObject2.SquaredZScoreInObjectSpace = new_instancemethod(_itkGaussianSpatialObjectPython.itkGaussianSpatialObject2_SquaredZScoreInObjectSpace, None, itkGaussianSpatialObject2)
itkGaussianSpatialObject2.SquaredZScoreInWorldSpace = new_instancemethod(_itkGaussianSpatialObjectPython.itkGaussianSpatialObject2_SquaredZScoreInWorldSpace, None, itkGaussianSpatialObject2)
itkGaussianSpatialObject2.ValueAtInObjectSpace = new_instancemethod(_itkGaussianSpatialObjectPython.itkGaussianSpatialObject2_ValueAtInObjectSpace, None, itkGaussianSpatialObject2)
itkGaussianSpatialObject2.GetEllipsoid = new_instancemethod(_itkGaussianSpatialObjectPython.itkGaussianSpatialObject2_GetEllipsoid, None, itkGaussianSpatialObject2)
itkGaussianSpatialObject2_swigregister = _itkGaussianSpatialObjectPython.itkGaussianSpatialObject2_swigregister
itkGaussianSpatialObject2_swigregister(itkGaussianSpatialObject2)

def itkGaussianSpatialObject2___New_orig__() -> "itkGaussianSpatialObject2_Pointer":
    """itkGaussianSpatialObject2___New_orig__() -> itkGaussianSpatialObject2_Pointer"""
    return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject2___New_orig__()

def itkGaussianSpatialObject2_cast(obj: 'itkLightObject') -> "itkGaussianSpatialObject2 *":
    """itkGaussianSpatialObject2_cast(itkLightObject obj) -> itkGaussianSpatialObject2"""
    return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject2_cast(obj)

class itkGaussianSpatialObject3(itkSpatialObjectBasePython.itkSpatialObject3):
    """


    Represents a multivariate Gaussian function.

    The Gaussian function G(x) is given by \\[ G(\\vec{x}) = m
    e^{-\\|\\S^{-1} \\vec{x}\\|^2 / 2}, \\] where m is a scaling
    factor set by SetMaximum(), and $\\S$ is the (invertible) matrix
    associated to the IndexToObjectTransform of the object multiplied by
    the Sigma parameter. If $\\S$ is symmetric and positive definite,
    and m is chosen so that the integral of G(x) is 1, then G will denote
    a normal distribution with mean 0 and covariance matrix $\\S
    \\times Sigma$.

    C++ includes: itkGaussianSpatialObject.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkGaussianSpatialObject3_Pointer":
        """__New_orig__() -> itkGaussianSpatialObject3_Pointer"""
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkGaussianSpatialObject3_Pointer":
        """Clone(itkGaussianSpatialObject3 self) -> itkGaussianSpatialObject3_Pointer"""
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject3_Clone(self)


    def SetRadiusInObjectSpace(self, _arg: 'double const') -> "void":
        """
        SetRadiusInObjectSpace(itkGaussianSpatialObject3 self, double const _arg)

        The Radius
        determines the bounding box, and which points are considered to be
        inside the SpatialObject. All points with z-score less than the radius
        are in the object. 
        """
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject3_SetRadiusInObjectSpace(self, _arg)


    def GetRadiusInObjectSpace(self) -> "double const &":
        """GetRadiusInObjectSpace(itkGaussianSpatialObject3 self) -> double const &"""
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject3_GetRadiusInObjectSpace(self)


    def SetSigmaInObjectSpace(self, _arg: 'double const') -> "void":
        """
        SetSigmaInObjectSpace(itkGaussianSpatialObject3 self, double const _arg)

        The Sigma
        parameter determines the fallout of the Gaussian inside of the region
        defined by the Radius parameter. 
        """
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject3_SetSigmaInObjectSpace(self, _arg)


    def GetSigmaInObjectSpace(self) -> "double const &":
        """GetSigmaInObjectSpace(itkGaussianSpatialObject3 self) -> double const &"""
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject3_GetSigmaInObjectSpace(self)


    def SetCenterInObjectSpace(self, _arg: 'itkPointD3') -> "void":
        """SetCenterInObjectSpace(itkGaussianSpatialObject3 self, itkPointD3 _arg)"""
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject3_SetCenterInObjectSpace(self, _arg)


    def GetCenterInObjectSpace(self) -> "itkPointD3 const &":
        """GetCenterInObjectSpace(itkGaussianSpatialObject3 self) -> itkPointD3"""
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject3_GetCenterInObjectSpace(self)


    def SetMaximum(self, _arg: 'double const') -> "void":
        """
        SetMaximum(itkGaussianSpatialObject3 self, double const _arg)

        The maximum value of the
        Gaussian (its value at the origin of the spatial object coordinate
        system). 
        """
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject3_SetMaximum(self, _arg)


    def GetMaximum(self) -> "double const &":
        """GetMaximum(itkGaussianSpatialObject3 self) -> double const &"""
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject3_GetMaximum(self)


    def SquaredZScoreInObjectSpace(self, point: 'itkPointD3') -> "double":
        """SquaredZScoreInObjectSpace(itkGaussianSpatialObject3 self, itkPointD3 point) -> double"""
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject3_SquaredZScoreInObjectSpace(self, point)


    def SquaredZScoreInWorldSpace(self, point: 'itkPointD3') -> "double":
        """SquaredZScoreInWorldSpace(itkGaussianSpatialObject3 self, itkPointD3 point) -> double"""
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject3_SquaredZScoreInWorldSpace(self, point)


    def ValueAtInObjectSpace(self, *args) -> "bool":
        """
        ValueAtInObjectSpace(itkGaussianSpatialObject3 self, itkPointD3 point, double & value, unsigned int depth=0, std::string const & name) -> bool
        ValueAtInObjectSpace(itkGaussianSpatialObject3 self, itkPointD3 point, double & value, unsigned int depth=0) -> bool
        ValueAtInObjectSpace(itkGaussianSpatialObject3 self, itkPointD3 point, double & value) -> bool

        Returns the
        value of the Gaussian at the given point. 
        """
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject3_ValueAtInObjectSpace(self, *args)


    def GetEllipsoid(self) -> "itkEllipseSpatialObject3_Pointer":
        """
        GetEllipsoid(itkGaussianSpatialObject3 self) -> itkEllipseSpatialObject3_Pointer

        Returns the
        sigma=m_Radius level set of the Gaussian function, as an
        EllipseSpatialObject. 
        """
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject3_GetEllipsoid(self)

    __swig_destroy__ = _itkGaussianSpatialObjectPython.delete_itkGaussianSpatialObject3

    def cast(obj: 'itkLightObject') -> "itkGaussianSpatialObject3 *":
        """cast(itkLightObject obj) -> itkGaussianSpatialObject3"""
        return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject3_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkGaussianSpatialObject3

        Create a new object of the class itkGaussianSpatialObject3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkGaussianSpatialObject3.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkGaussianSpatialObject3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkGaussianSpatialObject3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkGaussianSpatialObject3.Clone = new_instancemethod(_itkGaussianSpatialObjectPython.itkGaussianSpatialObject3_Clone, None, itkGaussianSpatialObject3)
itkGaussianSpatialObject3.SetRadiusInObjectSpace = new_instancemethod(_itkGaussianSpatialObjectPython.itkGaussianSpatialObject3_SetRadiusInObjectSpace, None, itkGaussianSpatialObject3)
itkGaussianSpatialObject3.GetRadiusInObjectSpace = new_instancemethod(_itkGaussianSpatialObjectPython.itkGaussianSpatialObject3_GetRadiusInObjectSpace, None, itkGaussianSpatialObject3)
itkGaussianSpatialObject3.SetSigmaInObjectSpace = new_instancemethod(_itkGaussianSpatialObjectPython.itkGaussianSpatialObject3_SetSigmaInObjectSpace, None, itkGaussianSpatialObject3)
itkGaussianSpatialObject3.GetSigmaInObjectSpace = new_instancemethod(_itkGaussianSpatialObjectPython.itkGaussianSpatialObject3_GetSigmaInObjectSpace, None, itkGaussianSpatialObject3)
itkGaussianSpatialObject3.SetCenterInObjectSpace = new_instancemethod(_itkGaussianSpatialObjectPython.itkGaussianSpatialObject3_SetCenterInObjectSpace, None, itkGaussianSpatialObject3)
itkGaussianSpatialObject3.GetCenterInObjectSpace = new_instancemethod(_itkGaussianSpatialObjectPython.itkGaussianSpatialObject3_GetCenterInObjectSpace, None, itkGaussianSpatialObject3)
itkGaussianSpatialObject3.SetMaximum = new_instancemethod(_itkGaussianSpatialObjectPython.itkGaussianSpatialObject3_SetMaximum, None, itkGaussianSpatialObject3)
itkGaussianSpatialObject3.GetMaximum = new_instancemethod(_itkGaussianSpatialObjectPython.itkGaussianSpatialObject3_GetMaximum, None, itkGaussianSpatialObject3)
itkGaussianSpatialObject3.SquaredZScoreInObjectSpace = new_instancemethod(_itkGaussianSpatialObjectPython.itkGaussianSpatialObject3_SquaredZScoreInObjectSpace, None, itkGaussianSpatialObject3)
itkGaussianSpatialObject3.SquaredZScoreInWorldSpace = new_instancemethod(_itkGaussianSpatialObjectPython.itkGaussianSpatialObject3_SquaredZScoreInWorldSpace, None, itkGaussianSpatialObject3)
itkGaussianSpatialObject3.ValueAtInObjectSpace = new_instancemethod(_itkGaussianSpatialObjectPython.itkGaussianSpatialObject3_ValueAtInObjectSpace, None, itkGaussianSpatialObject3)
itkGaussianSpatialObject3.GetEllipsoid = new_instancemethod(_itkGaussianSpatialObjectPython.itkGaussianSpatialObject3_GetEllipsoid, None, itkGaussianSpatialObject3)
itkGaussianSpatialObject3_swigregister = _itkGaussianSpatialObjectPython.itkGaussianSpatialObject3_swigregister
itkGaussianSpatialObject3_swigregister(itkGaussianSpatialObject3)

def itkGaussianSpatialObject3___New_orig__() -> "itkGaussianSpatialObject3_Pointer":
    """itkGaussianSpatialObject3___New_orig__() -> itkGaussianSpatialObject3_Pointer"""
    return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject3___New_orig__()

def itkGaussianSpatialObject3_cast(obj: 'itkLightObject') -> "itkGaussianSpatialObject3 *":
    """itkGaussianSpatialObject3_cast(itkLightObject obj) -> itkGaussianSpatialObject3"""
    return _itkGaussianSpatialObjectPython.itkGaussianSpatialObject3_cast(obj)



