# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _itkHConvexImageFilterPython.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_itkHConvexImageFilterPython', [dirname(__file__)])
        except ImportError:
            import _itkHConvexImageFilterPython
            return _itkHConvexImageFilterPython
        if fp is not None:
            try:
                _mod = imp.load_module('_itkHConvexImageFilterPython', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _itkHConvexImageFilterPython = swig_import_helper()
    del swig_import_helper
else:
    import _itkHConvexImageFilterPython
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


import itkImageToImageFilterAPython
import itkImagePython
import itkImageRegionPython
import itkSizePython
import pyBasePython
import ITKCommonBasePython
import itkIndexPython
import itkOffsetPython
import itkRGBAPixelPython
import itkFixedArrayPython
import stdcomplexPython
import itkRGBPixelPython
import itkMatrixPython
import vnl_matrix_fixedPython
import vnl_matrixPython
import vnl_vectorPython
import itkVectorPython
import vnl_vector_refPython
import itkCovariantVectorPython
import itkPointPython
import itkSymmetricSecondRankTensorPython
import itkImageSourcePython
import itkImageSourceCommonPython
import itkVectorImagePython
import itkVariableLengthVectorPython
import itkImageToImageFilterCommonPython

def itkHConvexImageFilterID3ID3_New():
  return itkHConvexImageFilterID3ID3.New()


def itkHConvexImageFilterID2ID2_New():
  return itkHConvexImageFilterID2ID2.New()


def itkHConvexImageFilterIF3IF3_New():
  return itkHConvexImageFilterIF3IF3.New()


def itkHConvexImageFilterIF2IF2_New():
  return itkHConvexImageFilterIF2IF2.New()


def itkHConvexImageFilterIUS3IUS3_New():
  return itkHConvexImageFilterIUS3IUS3.New()


def itkHConvexImageFilterIUS2IUS2_New():
  return itkHConvexImageFilterIUS2IUS2.New()


def itkHConvexImageFilterIUC3IUC3_New():
  return itkHConvexImageFilterIUC3IUC3.New()


def itkHConvexImageFilterIUC2IUC2_New():
  return itkHConvexImageFilterIUC2IUC2.New()


def itkHConvexImageFilterISS3ISS3_New():
  return itkHConvexImageFilterISS3ISS3.New()


def itkHConvexImageFilterISS2ISS2_New():
  return itkHConvexImageFilterISS2ISS2.New()

class itkHConvexImageFilterID2ID2(itkImageToImageFilterAPython.itkImageToImageFilterID2ID2):
    """


    Identify local maxima whose height above the baseline is greater than
    h.

    HConvexImageFilter extract local maxima that are more than h intensity
    units above the (local) background. This has the effect of extracting
    objects that are brighter than background by at least h intensity
    units.

    This filter uses the HMaximaImageFilter.

    Geodesic morphology and the H-Convex algorithm is described in Chapter
    6 of Pierre Soille's book "Morphological Image Analysis: Principles
    and Applications", Second Edition, Springer, 2003.

    See:   GrayscaleGeodesicDilateImageFilter, HMinimaImageFilter

    See:  MorphologyImageFilter, GrayscaleDilateImageFilter,
    GrayscaleFunctionDilateImageFilter, BinaryDilateImageFilter

    C++ includes: itkHConvexImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkHConvexImageFilterID2ID2_Pointer":
        """__New_orig__() -> itkHConvexImageFilterID2ID2_Pointer"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterID2ID2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkHConvexImageFilterID2ID2_Pointer":
        """Clone(itkHConvexImageFilterID2ID2 self) -> itkHConvexImageFilterID2ID2_Pointer"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterID2ID2_Clone(self)


    def SetHeight(self, _arg: 'double const') -> "void":
        """
        SetHeight(itkHConvexImageFilterID2ID2 self, double const _arg)

        Set/Get the height that a
        local maximum must be above the local background (local contrast) in
        order to survive the processing. Local maxima below this value are
        replaced with an estimate of the local background. 
        """
        return _itkHConvexImageFilterPython.itkHConvexImageFilterID2ID2_SetHeight(self, _arg)


    def GetHeight(self) -> "double":
        """GetHeight(itkHConvexImageFilterID2ID2 self) -> double"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterID2ID2_GetHeight(self)


    def SetFullyConnected(self, _arg: 'bool const') -> "void":
        """
        SetFullyConnected(itkHConvexImageFilterID2ID2 self, bool const _arg)

        Set/Get whether
        the connected components are defined strictly by face connectivity or
        by face+edge+vertex connectivity. Default is FullyConnectedOff. For
        objects that are 1 pixel wide, use FullyConnectedOn. 
        """
        return _itkHConvexImageFilterPython.itkHConvexImageFilterID2ID2_SetFullyConnected(self, _arg)


    def GetFullyConnected(self) -> "bool const &":
        """GetFullyConnected(itkHConvexImageFilterID2ID2 self) -> bool const &"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterID2ID2_GetFullyConnected(self)


    def FullyConnectedOn(self) -> "void":
        """FullyConnectedOn(itkHConvexImageFilterID2ID2 self)"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterID2ID2_FullyConnectedOn(self)


    def FullyConnectedOff(self) -> "void":
        """FullyConnectedOff(itkHConvexImageFilterID2ID2 self)"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterID2ID2_FullyConnectedOff(self)

    InputEqualityComparableCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterID2ID2_InputEqualityComparableCheck
    IntConvertibleToInputCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterID2ID2_IntConvertibleToInputCheck
    InputOStreamWritableCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterID2ID2_InputOStreamWritableCheck
    __swig_destroy__ = _itkHConvexImageFilterPython.delete_itkHConvexImageFilterID2ID2

    def cast(obj: 'itkLightObject') -> "itkHConvexImageFilterID2ID2 *":
        """cast(itkLightObject obj) -> itkHConvexImageFilterID2ID2"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterID2ID2_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkHConvexImageFilterID2ID2

        Create a new object of the class itkHConvexImageFilterID2ID2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkHConvexImageFilterID2ID2.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkHConvexImageFilterID2ID2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkHConvexImageFilterID2ID2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkHConvexImageFilterID2ID2.Clone = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterID2ID2_Clone, None, itkHConvexImageFilterID2ID2)
itkHConvexImageFilterID2ID2.SetHeight = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterID2ID2_SetHeight, None, itkHConvexImageFilterID2ID2)
itkHConvexImageFilterID2ID2.GetHeight = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterID2ID2_GetHeight, None, itkHConvexImageFilterID2ID2)
itkHConvexImageFilterID2ID2.SetFullyConnected = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterID2ID2_SetFullyConnected, None, itkHConvexImageFilterID2ID2)
itkHConvexImageFilterID2ID2.GetFullyConnected = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterID2ID2_GetFullyConnected, None, itkHConvexImageFilterID2ID2)
itkHConvexImageFilterID2ID2.FullyConnectedOn = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterID2ID2_FullyConnectedOn, None, itkHConvexImageFilterID2ID2)
itkHConvexImageFilterID2ID2.FullyConnectedOff = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterID2ID2_FullyConnectedOff, None, itkHConvexImageFilterID2ID2)
itkHConvexImageFilterID2ID2_swigregister = _itkHConvexImageFilterPython.itkHConvexImageFilterID2ID2_swigregister
itkHConvexImageFilterID2ID2_swigregister(itkHConvexImageFilterID2ID2)

def itkHConvexImageFilterID2ID2___New_orig__() -> "itkHConvexImageFilterID2ID2_Pointer":
    """itkHConvexImageFilterID2ID2___New_orig__() -> itkHConvexImageFilterID2ID2_Pointer"""
    return _itkHConvexImageFilterPython.itkHConvexImageFilterID2ID2___New_orig__()

def itkHConvexImageFilterID2ID2_cast(obj: 'itkLightObject') -> "itkHConvexImageFilterID2ID2 *":
    """itkHConvexImageFilterID2ID2_cast(itkLightObject obj) -> itkHConvexImageFilterID2ID2"""
    return _itkHConvexImageFilterPython.itkHConvexImageFilterID2ID2_cast(obj)

class itkHConvexImageFilterID3ID3(itkImageToImageFilterAPython.itkImageToImageFilterID3ID3):
    """


    Identify local maxima whose height above the baseline is greater than
    h.

    HConvexImageFilter extract local maxima that are more than h intensity
    units above the (local) background. This has the effect of extracting
    objects that are brighter than background by at least h intensity
    units.

    This filter uses the HMaximaImageFilter.

    Geodesic morphology and the H-Convex algorithm is described in Chapter
    6 of Pierre Soille's book "Morphological Image Analysis: Principles
    and Applications", Second Edition, Springer, 2003.

    See:   GrayscaleGeodesicDilateImageFilter, HMinimaImageFilter

    See:  MorphologyImageFilter, GrayscaleDilateImageFilter,
    GrayscaleFunctionDilateImageFilter, BinaryDilateImageFilter

    C++ includes: itkHConvexImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkHConvexImageFilterID3ID3_Pointer":
        """__New_orig__() -> itkHConvexImageFilterID3ID3_Pointer"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterID3ID3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkHConvexImageFilterID3ID3_Pointer":
        """Clone(itkHConvexImageFilterID3ID3 self) -> itkHConvexImageFilterID3ID3_Pointer"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterID3ID3_Clone(self)


    def SetHeight(self, _arg: 'double const') -> "void":
        """
        SetHeight(itkHConvexImageFilterID3ID3 self, double const _arg)

        Set/Get the height that a
        local maximum must be above the local background (local contrast) in
        order to survive the processing. Local maxima below this value are
        replaced with an estimate of the local background. 
        """
        return _itkHConvexImageFilterPython.itkHConvexImageFilterID3ID3_SetHeight(self, _arg)


    def GetHeight(self) -> "double":
        """GetHeight(itkHConvexImageFilterID3ID3 self) -> double"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterID3ID3_GetHeight(self)


    def SetFullyConnected(self, _arg: 'bool const') -> "void":
        """
        SetFullyConnected(itkHConvexImageFilterID3ID3 self, bool const _arg)

        Set/Get whether
        the connected components are defined strictly by face connectivity or
        by face+edge+vertex connectivity. Default is FullyConnectedOff. For
        objects that are 1 pixel wide, use FullyConnectedOn. 
        """
        return _itkHConvexImageFilterPython.itkHConvexImageFilterID3ID3_SetFullyConnected(self, _arg)


    def GetFullyConnected(self) -> "bool const &":
        """GetFullyConnected(itkHConvexImageFilterID3ID3 self) -> bool const &"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterID3ID3_GetFullyConnected(self)


    def FullyConnectedOn(self) -> "void":
        """FullyConnectedOn(itkHConvexImageFilterID3ID3 self)"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterID3ID3_FullyConnectedOn(self)


    def FullyConnectedOff(self) -> "void":
        """FullyConnectedOff(itkHConvexImageFilterID3ID3 self)"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterID3ID3_FullyConnectedOff(self)

    InputEqualityComparableCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterID3ID3_InputEqualityComparableCheck
    IntConvertibleToInputCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterID3ID3_IntConvertibleToInputCheck
    InputOStreamWritableCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterID3ID3_InputOStreamWritableCheck
    __swig_destroy__ = _itkHConvexImageFilterPython.delete_itkHConvexImageFilterID3ID3

    def cast(obj: 'itkLightObject') -> "itkHConvexImageFilterID3ID3 *":
        """cast(itkLightObject obj) -> itkHConvexImageFilterID3ID3"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterID3ID3_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkHConvexImageFilterID3ID3

        Create a new object of the class itkHConvexImageFilterID3ID3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkHConvexImageFilterID3ID3.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkHConvexImageFilterID3ID3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkHConvexImageFilterID3ID3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkHConvexImageFilterID3ID3.Clone = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterID3ID3_Clone, None, itkHConvexImageFilterID3ID3)
itkHConvexImageFilterID3ID3.SetHeight = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterID3ID3_SetHeight, None, itkHConvexImageFilterID3ID3)
itkHConvexImageFilterID3ID3.GetHeight = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterID3ID3_GetHeight, None, itkHConvexImageFilterID3ID3)
itkHConvexImageFilterID3ID3.SetFullyConnected = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterID3ID3_SetFullyConnected, None, itkHConvexImageFilterID3ID3)
itkHConvexImageFilterID3ID3.GetFullyConnected = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterID3ID3_GetFullyConnected, None, itkHConvexImageFilterID3ID3)
itkHConvexImageFilterID3ID3.FullyConnectedOn = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterID3ID3_FullyConnectedOn, None, itkHConvexImageFilterID3ID3)
itkHConvexImageFilterID3ID3.FullyConnectedOff = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterID3ID3_FullyConnectedOff, None, itkHConvexImageFilterID3ID3)
itkHConvexImageFilterID3ID3_swigregister = _itkHConvexImageFilterPython.itkHConvexImageFilterID3ID3_swigregister
itkHConvexImageFilterID3ID3_swigregister(itkHConvexImageFilterID3ID3)

def itkHConvexImageFilterID3ID3___New_orig__() -> "itkHConvexImageFilterID3ID3_Pointer":
    """itkHConvexImageFilterID3ID3___New_orig__() -> itkHConvexImageFilterID3ID3_Pointer"""
    return _itkHConvexImageFilterPython.itkHConvexImageFilterID3ID3___New_orig__()

def itkHConvexImageFilterID3ID3_cast(obj: 'itkLightObject') -> "itkHConvexImageFilterID3ID3 *":
    """itkHConvexImageFilterID3ID3_cast(itkLightObject obj) -> itkHConvexImageFilterID3ID3"""
    return _itkHConvexImageFilterPython.itkHConvexImageFilterID3ID3_cast(obj)

class itkHConvexImageFilterIF2IF2(itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    """


    Identify local maxima whose height above the baseline is greater than
    h.

    HConvexImageFilter extract local maxima that are more than h intensity
    units above the (local) background. This has the effect of extracting
    objects that are brighter than background by at least h intensity
    units.

    This filter uses the HMaximaImageFilter.

    Geodesic morphology and the H-Convex algorithm is described in Chapter
    6 of Pierre Soille's book "Morphological Image Analysis: Principles
    and Applications", Second Edition, Springer, 2003.

    See:   GrayscaleGeodesicDilateImageFilter, HMinimaImageFilter

    See:  MorphologyImageFilter, GrayscaleDilateImageFilter,
    GrayscaleFunctionDilateImageFilter, BinaryDilateImageFilter

    C++ includes: itkHConvexImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkHConvexImageFilterIF2IF2_Pointer":
        """__New_orig__() -> itkHConvexImageFilterIF2IF2_Pointer"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIF2IF2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkHConvexImageFilterIF2IF2_Pointer":
        """Clone(itkHConvexImageFilterIF2IF2 self) -> itkHConvexImageFilterIF2IF2_Pointer"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIF2IF2_Clone(self)


    def SetHeight(self, _arg: 'float const') -> "void":
        """
        SetHeight(itkHConvexImageFilterIF2IF2 self, float const _arg)

        Set/Get the height that a
        local maximum must be above the local background (local contrast) in
        order to survive the processing. Local maxima below this value are
        replaced with an estimate of the local background. 
        """
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIF2IF2_SetHeight(self, _arg)


    def GetHeight(self) -> "float":
        """GetHeight(itkHConvexImageFilterIF2IF2 self) -> float"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIF2IF2_GetHeight(self)


    def SetFullyConnected(self, _arg: 'bool const') -> "void":
        """
        SetFullyConnected(itkHConvexImageFilterIF2IF2 self, bool const _arg)

        Set/Get whether
        the connected components are defined strictly by face connectivity or
        by face+edge+vertex connectivity. Default is FullyConnectedOff. For
        objects that are 1 pixel wide, use FullyConnectedOn. 
        """
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIF2IF2_SetFullyConnected(self, _arg)


    def GetFullyConnected(self) -> "bool const &":
        """GetFullyConnected(itkHConvexImageFilterIF2IF2 self) -> bool const &"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIF2IF2_GetFullyConnected(self)


    def FullyConnectedOn(self) -> "void":
        """FullyConnectedOn(itkHConvexImageFilterIF2IF2 self)"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIF2IF2_FullyConnectedOn(self)


    def FullyConnectedOff(self) -> "void":
        """FullyConnectedOff(itkHConvexImageFilterIF2IF2 self)"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIF2IF2_FullyConnectedOff(self)

    InputEqualityComparableCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterIF2IF2_InputEqualityComparableCheck
    IntConvertibleToInputCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterIF2IF2_IntConvertibleToInputCheck
    InputOStreamWritableCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterIF2IF2_InputOStreamWritableCheck
    __swig_destroy__ = _itkHConvexImageFilterPython.delete_itkHConvexImageFilterIF2IF2

    def cast(obj: 'itkLightObject') -> "itkHConvexImageFilterIF2IF2 *":
        """cast(itkLightObject obj) -> itkHConvexImageFilterIF2IF2"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIF2IF2_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkHConvexImageFilterIF2IF2

        Create a new object of the class itkHConvexImageFilterIF2IF2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkHConvexImageFilterIF2IF2.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkHConvexImageFilterIF2IF2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkHConvexImageFilterIF2IF2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkHConvexImageFilterIF2IF2.Clone = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIF2IF2_Clone, None, itkHConvexImageFilterIF2IF2)
itkHConvexImageFilterIF2IF2.SetHeight = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIF2IF2_SetHeight, None, itkHConvexImageFilterIF2IF2)
itkHConvexImageFilterIF2IF2.GetHeight = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIF2IF2_GetHeight, None, itkHConvexImageFilterIF2IF2)
itkHConvexImageFilterIF2IF2.SetFullyConnected = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIF2IF2_SetFullyConnected, None, itkHConvexImageFilterIF2IF2)
itkHConvexImageFilterIF2IF2.GetFullyConnected = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIF2IF2_GetFullyConnected, None, itkHConvexImageFilterIF2IF2)
itkHConvexImageFilterIF2IF2.FullyConnectedOn = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIF2IF2_FullyConnectedOn, None, itkHConvexImageFilterIF2IF2)
itkHConvexImageFilterIF2IF2.FullyConnectedOff = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIF2IF2_FullyConnectedOff, None, itkHConvexImageFilterIF2IF2)
itkHConvexImageFilterIF2IF2_swigregister = _itkHConvexImageFilterPython.itkHConvexImageFilterIF2IF2_swigregister
itkHConvexImageFilterIF2IF2_swigregister(itkHConvexImageFilterIF2IF2)

def itkHConvexImageFilterIF2IF2___New_orig__() -> "itkHConvexImageFilterIF2IF2_Pointer":
    """itkHConvexImageFilterIF2IF2___New_orig__() -> itkHConvexImageFilterIF2IF2_Pointer"""
    return _itkHConvexImageFilterPython.itkHConvexImageFilterIF2IF2___New_orig__()

def itkHConvexImageFilterIF2IF2_cast(obj: 'itkLightObject') -> "itkHConvexImageFilterIF2IF2 *":
    """itkHConvexImageFilterIF2IF2_cast(itkLightObject obj) -> itkHConvexImageFilterIF2IF2"""
    return _itkHConvexImageFilterPython.itkHConvexImageFilterIF2IF2_cast(obj)

class itkHConvexImageFilterIF3IF3(itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    """


    Identify local maxima whose height above the baseline is greater than
    h.

    HConvexImageFilter extract local maxima that are more than h intensity
    units above the (local) background. This has the effect of extracting
    objects that are brighter than background by at least h intensity
    units.

    This filter uses the HMaximaImageFilter.

    Geodesic morphology and the H-Convex algorithm is described in Chapter
    6 of Pierre Soille's book "Morphological Image Analysis: Principles
    and Applications", Second Edition, Springer, 2003.

    See:   GrayscaleGeodesicDilateImageFilter, HMinimaImageFilter

    See:  MorphologyImageFilter, GrayscaleDilateImageFilter,
    GrayscaleFunctionDilateImageFilter, BinaryDilateImageFilter

    C++ includes: itkHConvexImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkHConvexImageFilterIF3IF3_Pointer":
        """__New_orig__() -> itkHConvexImageFilterIF3IF3_Pointer"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIF3IF3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkHConvexImageFilterIF3IF3_Pointer":
        """Clone(itkHConvexImageFilterIF3IF3 self) -> itkHConvexImageFilterIF3IF3_Pointer"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIF3IF3_Clone(self)


    def SetHeight(self, _arg: 'float const') -> "void":
        """
        SetHeight(itkHConvexImageFilterIF3IF3 self, float const _arg)

        Set/Get the height that a
        local maximum must be above the local background (local contrast) in
        order to survive the processing. Local maxima below this value are
        replaced with an estimate of the local background. 
        """
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIF3IF3_SetHeight(self, _arg)


    def GetHeight(self) -> "float":
        """GetHeight(itkHConvexImageFilterIF3IF3 self) -> float"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIF3IF3_GetHeight(self)


    def SetFullyConnected(self, _arg: 'bool const') -> "void":
        """
        SetFullyConnected(itkHConvexImageFilterIF3IF3 self, bool const _arg)

        Set/Get whether
        the connected components are defined strictly by face connectivity or
        by face+edge+vertex connectivity. Default is FullyConnectedOff. For
        objects that are 1 pixel wide, use FullyConnectedOn. 
        """
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIF3IF3_SetFullyConnected(self, _arg)


    def GetFullyConnected(self) -> "bool const &":
        """GetFullyConnected(itkHConvexImageFilterIF3IF3 self) -> bool const &"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIF3IF3_GetFullyConnected(self)


    def FullyConnectedOn(self) -> "void":
        """FullyConnectedOn(itkHConvexImageFilterIF3IF3 self)"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIF3IF3_FullyConnectedOn(self)


    def FullyConnectedOff(self) -> "void":
        """FullyConnectedOff(itkHConvexImageFilterIF3IF3 self)"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIF3IF3_FullyConnectedOff(self)

    InputEqualityComparableCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterIF3IF3_InputEqualityComparableCheck
    IntConvertibleToInputCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterIF3IF3_IntConvertibleToInputCheck
    InputOStreamWritableCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterIF3IF3_InputOStreamWritableCheck
    __swig_destroy__ = _itkHConvexImageFilterPython.delete_itkHConvexImageFilterIF3IF3

    def cast(obj: 'itkLightObject') -> "itkHConvexImageFilterIF3IF3 *":
        """cast(itkLightObject obj) -> itkHConvexImageFilterIF3IF3"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIF3IF3_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkHConvexImageFilterIF3IF3

        Create a new object of the class itkHConvexImageFilterIF3IF3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkHConvexImageFilterIF3IF3.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkHConvexImageFilterIF3IF3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkHConvexImageFilterIF3IF3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkHConvexImageFilterIF3IF3.Clone = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIF3IF3_Clone, None, itkHConvexImageFilterIF3IF3)
itkHConvexImageFilterIF3IF3.SetHeight = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIF3IF3_SetHeight, None, itkHConvexImageFilterIF3IF3)
itkHConvexImageFilterIF3IF3.GetHeight = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIF3IF3_GetHeight, None, itkHConvexImageFilterIF3IF3)
itkHConvexImageFilterIF3IF3.SetFullyConnected = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIF3IF3_SetFullyConnected, None, itkHConvexImageFilterIF3IF3)
itkHConvexImageFilterIF3IF3.GetFullyConnected = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIF3IF3_GetFullyConnected, None, itkHConvexImageFilterIF3IF3)
itkHConvexImageFilterIF3IF3.FullyConnectedOn = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIF3IF3_FullyConnectedOn, None, itkHConvexImageFilterIF3IF3)
itkHConvexImageFilterIF3IF3.FullyConnectedOff = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIF3IF3_FullyConnectedOff, None, itkHConvexImageFilterIF3IF3)
itkHConvexImageFilterIF3IF3_swigregister = _itkHConvexImageFilterPython.itkHConvexImageFilterIF3IF3_swigregister
itkHConvexImageFilterIF3IF3_swigregister(itkHConvexImageFilterIF3IF3)

def itkHConvexImageFilterIF3IF3___New_orig__() -> "itkHConvexImageFilterIF3IF3_Pointer":
    """itkHConvexImageFilterIF3IF3___New_orig__() -> itkHConvexImageFilterIF3IF3_Pointer"""
    return _itkHConvexImageFilterPython.itkHConvexImageFilterIF3IF3___New_orig__()

def itkHConvexImageFilterIF3IF3_cast(obj: 'itkLightObject') -> "itkHConvexImageFilterIF3IF3 *":
    """itkHConvexImageFilterIF3IF3_cast(itkLightObject obj) -> itkHConvexImageFilterIF3IF3"""
    return _itkHConvexImageFilterPython.itkHConvexImageFilterIF3IF3_cast(obj)

class itkHConvexImageFilterISS2ISS2(itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    """


    Identify local maxima whose height above the baseline is greater than
    h.

    HConvexImageFilter extract local maxima that are more than h intensity
    units above the (local) background. This has the effect of extracting
    objects that are brighter than background by at least h intensity
    units.

    This filter uses the HMaximaImageFilter.

    Geodesic morphology and the H-Convex algorithm is described in Chapter
    6 of Pierre Soille's book "Morphological Image Analysis: Principles
    and Applications", Second Edition, Springer, 2003.

    See:   GrayscaleGeodesicDilateImageFilter, HMinimaImageFilter

    See:  MorphologyImageFilter, GrayscaleDilateImageFilter,
    GrayscaleFunctionDilateImageFilter, BinaryDilateImageFilter

    C++ includes: itkHConvexImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkHConvexImageFilterISS2ISS2_Pointer":
        """__New_orig__() -> itkHConvexImageFilterISS2ISS2_Pointer"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterISS2ISS2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkHConvexImageFilterISS2ISS2_Pointer":
        """Clone(itkHConvexImageFilterISS2ISS2 self) -> itkHConvexImageFilterISS2ISS2_Pointer"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterISS2ISS2_Clone(self)


    def SetHeight(self, _arg: 'short const') -> "void":
        """
        SetHeight(itkHConvexImageFilterISS2ISS2 self, short const _arg)

        Set/Get the height that a
        local maximum must be above the local background (local contrast) in
        order to survive the processing. Local maxima below this value are
        replaced with an estimate of the local background. 
        """
        return _itkHConvexImageFilterPython.itkHConvexImageFilterISS2ISS2_SetHeight(self, _arg)


    def GetHeight(self) -> "short":
        """GetHeight(itkHConvexImageFilterISS2ISS2 self) -> short"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterISS2ISS2_GetHeight(self)


    def SetFullyConnected(self, _arg: 'bool const') -> "void":
        """
        SetFullyConnected(itkHConvexImageFilterISS2ISS2 self, bool const _arg)

        Set/Get whether
        the connected components are defined strictly by face connectivity or
        by face+edge+vertex connectivity. Default is FullyConnectedOff. For
        objects that are 1 pixel wide, use FullyConnectedOn. 
        """
        return _itkHConvexImageFilterPython.itkHConvexImageFilterISS2ISS2_SetFullyConnected(self, _arg)


    def GetFullyConnected(self) -> "bool const &":
        """GetFullyConnected(itkHConvexImageFilterISS2ISS2 self) -> bool const &"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterISS2ISS2_GetFullyConnected(self)


    def FullyConnectedOn(self) -> "void":
        """FullyConnectedOn(itkHConvexImageFilterISS2ISS2 self)"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterISS2ISS2_FullyConnectedOn(self)


    def FullyConnectedOff(self) -> "void":
        """FullyConnectedOff(itkHConvexImageFilterISS2ISS2 self)"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterISS2ISS2_FullyConnectedOff(self)

    InputEqualityComparableCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterISS2ISS2_InputEqualityComparableCheck
    IntConvertibleToInputCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterISS2ISS2_IntConvertibleToInputCheck
    InputOStreamWritableCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterISS2ISS2_InputOStreamWritableCheck
    __swig_destroy__ = _itkHConvexImageFilterPython.delete_itkHConvexImageFilterISS2ISS2

    def cast(obj: 'itkLightObject') -> "itkHConvexImageFilterISS2ISS2 *":
        """cast(itkLightObject obj) -> itkHConvexImageFilterISS2ISS2"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterISS2ISS2_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkHConvexImageFilterISS2ISS2

        Create a new object of the class itkHConvexImageFilterISS2ISS2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkHConvexImageFilterISS2ISS2.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkHConvexImageFilterISS2ISS2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkHConvexImageFilterISS2ISS2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkHConvexImageFilterISS2ISS2.Clone = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterISS2ISS2_Clone, None, itkHConvexImageFilterISS2ISS2)
itkHConvexImageFilterISS2ISS2.SetHeight = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterISS2ISS2_SetHeight, None, itkHConvexImageFilterISS2ISS2)
itkHConvexImageFilterISS2ISS2.GetHeight = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterISS2ISS2_GetHeight, None, itkHConvexImageFilterISS2ISS2)
itkHConvexImageFilterISS2ISS2.SetFullyConnected = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterISS2ISS2_SetFullyConnected, None, itkHConvexImageFilterISS2ISS2)
itkHConvexImageFilterISS2ISS2.GetFullyConnected = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterISS2ISS2_GetFullyConnected, None, itkHConvexImageFilterISS2ISS2)
itkHConvexImageFilterISS2ISS2.FullyConnectedOn = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterISS2ISS2_FullyConnectedOn, None, itkHConvexImageFilterISS2ISS2)
itkHConvexImageFilterISS2ISS2.FullyConnectedOff = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterISS2ISS2_FullyConnectedOff, None, itkHConvexImageFilterISS2ISS2)
itkHConvexImageFilterISS2ISS2_swigregister = _itkHConvexImageFilterPython.itkHConvexImageFilterISS2ISS2_swigregister
itkHConvexImageFilterISS2ISS2_swigregister(itkHConvexImageFilterISS2ISS2)

def itkHConvexImageFilterISS2ISS2___New_orig__() -> "itkHConvexImageFilterISS2ISS2_Pointer":
    """itkHConvexImageFilterISS2ISS2___New_orig__() -> itkHConvexImageFilterISS2ISS2_Pointer"""
    return _itkHConvexImageFilterPython.itkHConvexImageFilterISS2ISS2___New_orig__()

def itkHConvexImageFilterISS2ISS2_cast(obj: 'itkLightObject') -> "itkHConvexImageFilterISS2ISS2 *":
    """itkHConvexImageFilterISS2ISS2_cast(itkLightObject obj) -> itkHConvexImageFilterISS2ISS2"""
    return _itkHConvexImageFilterPython.itkHConvexImageFilterISS2ISS2_cast(obj)

class itkHConvexImageFilterISS3ISS3(itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    """


    Identify local maxima whose height above the baseline is greater than
    h.

    HConvexImageFilter extract local maxima that are more than h intensity
    units above the (local) background. This has the effect of extracting
    objects that are brighter than background by at least h intensity
    units.

    This filter uses the HMaximaImageFilter.

    Geodesic morphology and the H-Convex algorithm is described in Chapter
    6 of Pierre Soille's book "Morphological Image Analysis: Principles
    and Applications", Second Edition, Springer, 2003.

    See:   GrayscaleGeodesicDilateImageFilter, HMinimaImageFilter

    See:  MorphologyImageFilter, GrayscaleDilateImageFilter,
    GrayscaleFunctionDilateImageFilter, BinaryDilateImageFilter

    C++ includes: itkHConvexImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkHConvexImageFilterISS3ISS3_Pointer":
        """__New_orig__() -> itkHConvexImageFilterISS3ISS3_Pointer"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterISS3ISS3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkHConvexImageFilterISS3ISS3_Pointer":
        """Clone(itkHConvexImageFilterISS3ISS3 self) -> itkHConvexImageFilterISS3ISS3_Pointer"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterISS3ISS3_Clone(self)


    def SetHeight(self, _arg: 'short const') -> "void":
        """
        SetHeight(itkHConvexImageFilterISS3ISS3 self, short const _arg)

        Set/Get the height that a
        local maximum must be above the local background (local contrast) in
        order to survive the processing. Local maxima below this value are
        replaced with an estimate of the local background. 
        """
        return _itkHConvexImageFilterPython.itkHConvexImageFilterISS3ISS3_SetHeight(self, _arg)


    def GetHeight(self) -> "short":
        """GetHeight(itkHConvexImageFilterISS3ISS3 self) -> short"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterISS3ISS3_GetHeight(self)


    def SetFullyConnected(self, _arg: 'bool const') -> "void":
        """
        SetFullyConnected(itkHConvexImageFilterISS3ISS3 self, bool const _arg)

        Set/Get whether
        the connected components are defined strictly by face connectivity or
        by face+edge+vertex connectivity. Default is FullyConnectedOff. For
        objects that are 1 pixel wide, use FullyConnectedOn. 
        """
        return _itkHConvexImageFilterPython.itkHConvexImageFilterISS3ISS3_SetFullyConnected(self, _arg)


    def GetFullyConnected(self) -> "bool const &":
        """GetFullyConnected(itkHConvexImageFilterISS3ISS3 self) -> bool const &"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterISS3ISS3_GetFullyConnected(self)


    def FullyConnectedOn(self) -> "void":
        """FullyConnectedOn(itkHConvexImageFilterISS3ISS3 self)"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterISS3ISS3_FullyConnectedOn(self)


    def FullyConnectedOff(self) -> "void":
        """FullyConnectedOff(itkHConvexImageFilterISS3ISS3 self)"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterISS3ISS3_FullyConnectedOff(self)

    InputEqualityComparableCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterISS3ISS3_InputEqualityComparableCheck
    IntConvertibleToInputCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterISS3ISS3_IntConvertibleToInputCheck
    InputOStreamWritableCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterISS3ISS3_InputOStreamWritableCheck
    __swig_destroy__ = _itkHConvexImageFilterPython.delete_itkHConvexImageFilterISS3ISS3

    def cast(obj: 'itkLightObject') -> "itkHConvexImageFilterISS3ISS3 *":
        """cast(itkLightObject obj) -> itkHConvexImageFilterISS3ISS3"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterISS3ISS3_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkHConvexImageFilterISS3ISS3

        Create a new object of the class itkHConvexImageFilterISS3ISS3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkHConvexImageFilterISS3ISS3.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkHConvexImageFilterISS3ISS3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkHConvexImageFilterISS3ISS3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkHConvexImageFilterISS3ISS3.Clone = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterISS3ISS3_Clone, None, itkHConvexImageFilterISS3ISS3)
itkHConvexImageFilterISS3ISS3.SetHeight = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterISS3ISS3_SetHeight, None, itkHConvexImageFilterISS3ISS3)
itkHConvexImageFilterISS3ISS3.GetHeight = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterISS3ISS3_GetHeight, None, itkHConvexImageFilterISS3ISS3)
itkHConvexImageFilterISS3ISS3.SetFullyConnected = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterISS3ISS3_SetFullyConnected, None, itkHConvexImageFilterISS3ISS3)
itkHConvexImageFilterISS3ISS3.GetFullyConnected = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterISS3ISS3_GetFullyConnected, None, itkHConvexImageFilterISS3ISS3)
itkHConvexImageFilterISS3ISS3.FullyConnectedOn = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterISS3ISS3_FullyConnectedOn, None, itkHConvexImageFilterISS3ISS3)
itkHConvexImageFilterISS3ISS3.FullyConnectedOff = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterISS3ISS3_FullyConnectedOff, None, itkHConvexImageFilterISS3ISS3)
itkHConvexImageFilterISS3ISS3_swigregister = _itkHConvexImageFilterPython.itkHConvexImageFilterISS3ISS3_swigregister
itkHConvexImageFilterISS3ISS3_swigregister(itkHConvexImageFilterISS3ISS3)

def itkHConvexImageFilterISS3ISS3___New_orig__() -> "itkHConvexImageFilterISS3ISS3_Pointer":
    """itkHConvexImageFilterISS3ISS3___New_orig__() -> itkHConvexImageFilterISS3ISS3_Pointer"""
    return _itkHConvexImageFilterPython.itkHConvexImageFilterISS3ISS3___New_orig__()

def itkHConvexImageFilterISS3ISS3_cast(obj: 'itkLightObject') -> "itkHConvexImageFilterISS3ISS3 *":
    """itkHConvexImageFilterISS3ISS3_cast(itkLightObject obj) -> itkHConvexImageFilterISS3ISS3"""
    return _itkHConvexImageFilterPython.itkHConvexImageFilterISS3ISS3_cast(obj)

class itkHConvexImageFilterIUC2IUC2(itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    """


    Identify local maxima whose height above the baseline is greater than
    h.

    HConvexImageFilter extract local maxima that are more than h intensity
    units above the (local) background. This has the effect of extracting
    objects that are brighter than background by at least h intensity
    units.

    This filter uses the HMaximaImageFilter.

    Geodesic morphology and the H-Convex algorithm is described in Chapter
    6 of Pierre Soille's book "Morphological Image Analysis: Principles
    and Applications", Second Edition, Springer, 2003.

    See:   GrayscaleGeodesicDilateImageFilter, HMinimaImageFilter

    See:  MorphologyImageFilter, GrayscaleDilateImageFilter,
    GrayscaleFunctionDilateImageFilter, BinaryDilateImageFilter

    C++ includes: itkHConvexImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkHConvexImageFilterIUC2IUC2_Pointer":
        """__New_orig__() -> itkHConvexImageFilterIUC2IUC2_Pointer"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUC2IUC2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkHConvexImageFilterIUC2IUC2_Pointer":
        """Clone(itkHConvexImageFilterIUC2IUC2 self) -> itkHConvexImageFilterIUC2IUC2_Pointer"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUC2IUC2_Clone(self)


    def SetHeight(self, _arg: 'unsigned char const') -> "void":
        """
        SetHeight(itkHConvexImageFilterIUC2IUC2 self, unsigned char const _arg)

        Set/Get the height that a
        local maximum must be above the local background (local contrast) in
        order to survive the processing. Local maxima below this value are
        replaced with an estimate of the local background. 
        """
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUC2IUC2_SetHeight(self, _arg)


    def GetHeight(self) -> "unsigned char":
        """GetHeight(itkHConvexImageFilterIUC2IUC2 self) -> unsigned char"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUC2IUC2_GetHeight(self)


    def SetFullyConnected(self, _arg: 'bool const') -> "void":
        """
        SetFullyConnected(itkHConvexImageFilterIUC2IUC2 self, bool const _arg)

        Set/Get whether
        the connected components are defined strictly by face connectivity or
        by face+edge+vertex connectivity. Default is FullyConnectedOff. For
        objects that are 1 pixel wide, use FullyConnectedOn. 
        """
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUC2IUC2_SetFullyConnected(self, _arg)


    def GetFullyConnected(self) -> "bool const &":
        """GetFullyConnected(itkHConvexImageFilterIUC2IUC2 self) -> bool const &"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUC2IUC2_GetFullyConnected(self)


    def FullyConnectedOn(self) -> "void":
        """FullyConnectedOn(itkHConvexImageFilterIUC2IUC2 self)"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUC2IUC2_FullyConnectedOn(self)


    def FullyConnectedOff(self) -> "void":
        """FullyConnectedOff(itkHConvexImageFilterIUC2IUC2 self)"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUC2IUC2_FullyConnectedOff(self)

    InputEqualityComparableCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterIUC2IUC2_InputEqualityComparableCheck
    IntConvertibleToInputCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterIUC2IUC2_IntConvertibleToInputCheck
    InputOStreamWritableCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterIUC2IUC2_InputOStreamWritableCheck
    __swig_destroy__ = _itkHConvexImageFilterPython.delete_itkHConvexImageFilterIUC2IUC2

    def cast(obj: 'itkLightObject') -> "itkHConvexImageFilterIUC2IUC2 *":
        """cast(itkLightObject obj) -> itkHConvexImageFilterIUC2IUC2"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUC2IUC2_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkHConvexImageFilterIUC2IUC2

        Create a new object of the class itkHConvexImageFilterIUC2IUC2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkHConvexImageFilterIUC2IUC2.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkHConvexImageFilterIUC2IUC2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkHConvexImageFilterIUC2IUC2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkHConvexImageFilterIUC2IUC2.Clone = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIUC2IUC2_Clone, None, itkHConvexImageFilterIUC2IUC2)
itkHConvexImageFilterIUC2IUC2.SetHeight = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIUC2IUC2_SetHeight, None, itkHConvexImageFilterIUC2IUC2)
itkHConvexImageFilterIUC2IUC2.GetHeight = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIUC2IUC2_GetHeight, None, itkHConvexImageFilterIUC2IUC2)
itkHConvexImageFilterIUC2IUC2.SetFullyConnected = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIUC2IUC2_SetFullyConnected, None, itkHConvexImageFilterIUC2IUC2)
itkHConvexImageFilterIUC2IUC2.GetFullyConnected = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIUC2IUC2_GetFullyConnected, None, itkHConvexImageFilterIUC2IUC2)
itkHConvexImageFilterIUC2IUC2.FullyConnectedOn = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIUC2IUC2_FullyConnectedOn, None, itkHConvexImageFilterIUC2IUC2)
itkHConvexImageFilterIUC2IUC2.FullyConnectedOff = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIUC2IUC2_FullyConnectedOff, None, itkHConvexImageFilterIUC2IUC2)
itkHConvexImageFilterIUC2IUC2_swigregister = _itkHConvexImageFilterPython.itkHConvexImageFilterIUC2IUC2_swigregister
itkHConvexImageFilterIUC2IUC2_swigregister(itkHConvexImageFilterIUC2IUC2)

def itkHConvexImageFilterIUC2IUC2___New_orig__() -> "itkHConvexImageFilterIUC2IUC2_Pointer":
    """itkHConvexImageFilterIUC2IUC2___New_orig__() -> itkHConvexImageFilterIUC2IUC2_Pointer"""
    return _itkHConvexImageFilterPython.itkHConvexImageFilterIUC2IUC2___New_orig__()

def itkHConvexImageFilterIUC2IUC2_cast(obj: 'itkLightObject') -> "itkHConvexImageFilterIUC2IUC2 *":
    """itkHConvexImageFilterIUC2IUC2_cast(itkLightObject obj) -> itkHConvexImageFilterIUC2IUC2"""
    return _itkHConvexImageFilterPython.itkHConvexImageFilterIUC2IUC2_cast(obj)

class itkHConvexImageFilterIUC3IUC3(itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    """


    Identify local maxima whose height above the baseline is greater than
    h.

    HConvexImageFilter extract local maxima that are more than h intensity
    units above the (local) background. This has the effect of extracting
    objects that are brighter than background by at least h intensity
    units.

    This filter uses the HMaximaImageFilter.

    Geodesic morphology and the H-Convex algorithm is described in Chapter
    6 of Pierre Soille's book "Morphological Image Analysis: Principles
    and Applications", Second Edition, Springer, 2003.

    See:   GrayscaleGeodesicDilateImageFilter, HMinimaImageFilter

    See:  MorphologyImageFilter, GrayscaleDilateImageFilter,
    GrayscaleFunctionDilateImageFilter, BinaryDilateImageFilter

    C++ includes: itkHConvexImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkHConvexImageFilterIUC3IUC3_Pointer":
        """__New_orig__() -> itkHConvexImageFilterIUC3IUC3_Pointer"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUC3IUC3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkHConvexImageFilterIUC3IUC3_Pointer":
        """Clone(itkHConvexImageFilterIUC3IUC3 self) -> itkHConvexImageFilterIUC3IUC3_Pointer"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUC3IUC3_Clone(self)


    def SetHeight(self, _arg: 'unsigned char const') -> "void":
        """
        SetHeight(itkHConvexImageFilterIUC3IUC3 self, unsigned char const _arg)

        Set/Get the height that a
        local maximum must be above the local background (local contrast) in
        order to survive the processing. Local maxima below this value are
        replaced with an estimate of the local background. 
        """
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUC3IUC3_SetHeight(self, _arg)


    def GetHeight(self) -> "unsigned char":
        """GetHeight(itkHConvexImageFilterIUC3IUC3 self) -> unsigned char"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUC3IUC3_GetHeight(self)


    def SetFullyConnected(self, _arg: 'bool const') -> "void":
        """
        SetFullyConnected(itkHConvexImageFilterIUC3IUC3 self, bool const _arg)

        Set/Get whether
        the connected components are defined strictly by face connectivity or
        by face+edge+vertex connectivity. Default is FullyConnectedOff. For
        objects that are 1 pixel wide, use FullyConnectedOn. 
        """
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUC3IUC3_SetFullyConnected(self, _arg)


    def GetFullyConnected(self) -> "bool const &":
        """GetFullyConnected(itkHConvexImageFilterIUC3IUC3 self) -> bool const &"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUC3IUC3_GetFullyConnected(self)


    def FullyConnectedOn(self) -> "void":
        """FullyConnectedOn(itkHConvexImageFilterIUC3IUC3 self)"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUC3IUC3_FullyConnectedOn(self)


    def FullyConnectedOff(self) -> "void":
        """FullyConnectedOff(itkHConvexImageFilterIUC3IUC3 self)"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUC3IUC3_FullyConnectedOff(self)

    InputEqualityComparableCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterIUC3IUC3_InputEqualityComparableCheck
    IntConvertibleToInputCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterIUC3IUC3_IntConvertibleToInputCheck
    InputOStreamWritableCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterIUC3IUC3_InputOStreamWritableCheck
    __swig_destroy__ = _itkHConvexImageFilterPython.delete_itkHConvexImageFilterIUC3IUC3

    def cast(obj: 'itkLightObject') -> "itkHConvexImageFilterIUC3IUC3 *":
        """cast(itkLightObject obj) -> itkHConvexImageFilterIUC3IUC3"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUC3IUC3_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkHConvexImageFilterIUC3IUC3

        Create a new object of the class itkHConvexImageFilterIUC3IUC3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkHConvexImageFilterIUC3IUC3.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkHConvexImageFilterIUC3IUC3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkHConvexImageFilterIUC3IUC3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkHConvexImageFilterIUC3IUC3.Clone = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIUC3IUC3_Clone, None, itkHConvexImageFilterIUC3IUC3)
itkHConvexImageFilterIUC3IUC3.SetHeight = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIUC3IUC3_SetHeight, None, itkHConvexImageFilterIUC3IUC3)
itkHConvexImageFilterIUC3IUC3.GetHeight = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIUC3IUC3_GetHeight, None, itkHConvexImageFilterIUC3IUC3)
itkHConvexImageFilterIUC3IUC3.SetFullyConnected = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIUC3IUC3_SetFullyConnected, None, itkHConvexImageFilterIUC3IUC3)
itkHConvexImageFilterIUC3IUC3.GetFullyConnected = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIUC3IUC3_GetFullyConnected, None, itkHConvexImageFilterIUC3IUC3)
itkHConvexImageFilterIUC3IUC3.FullyConnectedOn = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIUC3IUC3_FullyConnectedOn, None, itkHConvexImageFilterIUC3IUC3)
itkHConvexImageFilterIUC3IUC3.FullyConnectedOff = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIUC3IUC3_FullyConnectedOff, None, itkHConvexImageFilterIUC3IUC3)
itkHConvexImageFilterIUC3IUC3_swigregister = _itkHConvexImageFilterPython.itkHConvexImageFilterIUC3IUC3_swigregister
itkHConvexImageFilterIUC3IUC3_swigregister(itkHConvexImageFilterIUC3IUC3)

def itkHConvexImageFilterIUC3IUC3___New_orig__() -> "itkHConvexImageFilterIUC3IUC3_Pointer":
    """itkHConvexImageFilterIUC3IUC3___New_orig__() -> itkHConvexImageFilterIUC3IUC3_Pointer"""
    return _itkHConvexImageFilterPython.itkHConvexImageFilterIUC3IUC3___New_orig__()

def itkHConvexImageFilterIUC3IUC3_cast(obj: 'itkLightObject') -> "itkHConvexImageFilterIUC3IUC3 *":
    """itkHConvexImageFilterIUC3IUC3_cast(itkLightObject obj) -> itkHConvexImageFilterIUC3IUC3"""
    return _itkHConvexImageFilterPython.itkHConvexImageFilterIUC3IUC3_cast(obj)

class itkHConvexImageFilterIUS2IUS2(itkImageToImageFilterAPython.itkImageToImageFilterIUS2IUS2):
    """


    Identify local maxima whose height above the baseline is greater than
    h.

    HConvexImageFilter extract local maxima that are more than h intensity
    units above the (local) background. This has the effect of extracting
    objects that are brighter than background by at least h intensity
    units.

    This filter uses the HMaximaImageFilter.

    Geodesic morphology and the H-Convex algorithm is described in Chapter
    6 of Pierre Soille's book "Morphological Image Analysis: Principles
    and Applications", Second Edition, Springer, 2003.

    See:   GrayscaleGeodesicDilateImageFilter, HMinimaImageFilter

    See:  MorphologyImageFilter, GrayscaleDilateImageFilter,
    GrayscaleFunctionDilateImageFilter, BinaryDilateImageFilter

    C++ includes: itkHConvexImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkHConvexImageFilterIUS2IUS2_Pointer":
        """__New_orig__() -> itkHConvexImageFilterIUS2IUS2_Pointer"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUS2IUS2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkHConvexImageFilterIUS2IUS2_Pointer":
        """Clone(itkHConvexImageFilterIUS2IUS2 self) -> itkHConvexImageFilterIUS2IUS2_Pointer"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUS2IUS2_Clone(self)


    def SetHeight(self, _arg: 'unsigned short const') -> "void":
        """
        SetHeight(itkHConvexImageFilterIUS2IUS2 self, unsigned short const _arg)

        Set/Get the height that a
        local maximum must be above the local background (local contrast) in
        order to survive the processing. Local maxima below this value are
        replaced with an estimate of the local background. 
        """
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUS2IUS2_SetHeight(self, _arg)


    def GetHeight(self) -> "unsigned short":
        """GetHeight(itkHConvexImageFilterIUS2IUS2 self) -> unsigned short"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUS2IUS2_GetHeight(self)


    def SetFullyConnected(self, _arg: 'bool const') -> "void":
        """
        SetFullyConnected(itkHConvexImageFilterIUS2IUS2 self, bool const _arg)

        Set/Get whether
        the connected components are defined strictly by face connectivity or
        by face+edge+vertex connectivity. Default is FullyConnectedOff. For
        objects that are 1 pixel wide, use FullyConnectedOn. 
        """
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUS2IUS2_SetFullyConnected(self, _arg)


    def GetFullyConnected(self) -> "bool const &":
        """GetFullyConnected(itkHConvexImageFilterIUS2IUS2 self) -> bool const &"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUS2IUS2_GetFullyConnected(self)


    def FullyConnectedOn(self) -> "void":
        """FullyConnectedOn(itkHConvexImageFilterIUS2IUS2 self)"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUS2IUS2_FullyConnectedOn(self)


    def FullyConnectedOff(self) -> "void":
        """FullyConnectedOff(itkHConvexImageFilterIUS2IUS2 self)"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUS2IUS2_FullyConnectedOff(self)

    InputEqualityComparableCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterIUS2IUS2_InputEqualityComparableCheck
    IntConvertibleToInputCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterIUS2IUS2_IntConvertibleToInputCheck
    InputOStreamWritableCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterIUS2IUS2_InputOStreamWritableCheck
    __swig_destroy__ = _itkHConvexImageFilterPython.delete_itkHConvexImageFilterIUS2IUS2

    def cast(obj: 'itkLightObject') -> "itkHConvexImageFilterIUS2IUS2 *":
        """cast(itkLightObject obj) -> itkHConvexImageFilterIUS2IUS2"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUS2IUS2_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkHConvexImageFilterIUS2IUS2

        Create a new object of the class itkHConvexImageFilterIUS2IUS2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkHConvexImageFilterIUS2IUS2.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkHConvexImageFilterIUS2IUS2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkHConvexImageFilterIUS2IUS2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkHConvexImageFilterIUS2IUS2.Clone = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIUS2IUS2_Clone, None, itkHConvexImageFilterIUS2IUS2)
itkHConvexImageFilterIUS2IUS2.SetHeight = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIUS2IUS2_SetHeight, None, itkHConvexImageFilterIUS2IUS2)
itkHConvexImageFilterIUS2IUS2.GetHeight = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIUS2IUS2_GetHeight, None, itkHConvexImageFilterIUS2IUS2)
itkHConvexImageFilterIUS2IUS2.SetFullyConnected = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIUS2IUS2_SetFullyConnected, None, itkHConvexImageFilterIUS2IUS2)
itkHConvexImageFilterIUS2IUS2.GetFullyConnected = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIUS2IUS2_GetFullyConnected, None, itkHConvexImageFilterIUS2IUS2)
itkHConvexImageFilterIUS2IUS2.FullyConnectedOn = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIUS2IUS2_FullyConnectedOn, None, itkHConvexImageFilterIUS2IUS2)
itkHConvexImageFilterIUS2IUS2.FullyConnectedOff = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIUS2IUS2_FullyConnectedOff, None, itkHConvexImageFilterIUS2IUS2)
itkHConvexImageFilterIUS2IUS2_swigregister = _itkHConvexImageFilterPython.itkHConvexImageFilterIUS2IUS2_swigregister
itkHConvexImageFilterIUS2IUS2_swigregister(itkHConvexImageFilterIUS2IUS2)

def itkHConvexImageFilterIUS2IUS2___New_orig__() -> "itkHConvexImageFilterIUS2IUS2_Pointer":
    """itkHConvexImageFilterIUS2IUS2___New_orig__() -> itkHConvexImageFilterIUS2IUS2_Pointer"""
    return _itkHConvexImageFilterPython.itkHConvexImageFilterIUS2IUS2___New_orig__()

def itkHConvexImageFilterIUS2IUS2_cast(obj: 'itkLightObject') -> "itkHConvexImageFilterIUS2IUS2 *":
    """itkHConvexImageFilterIUS2IUS2_cast(itkLightObject obj) -> itkHConvexImageFilterIUS2IUS2"""
    return _itkHConvexImageFilterPython.itkHConvexImageFilterIUS2IUS2_cast(obj)

class itkHConvexImageFilterIUS3IUS3(itkImageToImageFilterAPython.itkImageToImageFilterIUS3IUS3):
    """


    Identify local maxima whose height above the baseline is greater than
    h.

    HConvexImageFilter extract local maxima that are more than h intensity
    units above the (local) background. This has the effect of extracting
    objects that are brighter than background by at least h intensity
    units.

    This filter uses the HMaximaImageFilter.

    Geodesic morphology and the H-Convex algorithm is described in Chapter
    6 of Pierre Soille's book "Morphological Image Analysis: Principles
    and Applications", Second Edition, Springer, 2003.

    See:   GrayscaleGeodesicDilateImageFilter, HMinimaImageFilter

    See:  MorphologyImageFilter, GrayscaleDilateImageFilter,
    GrayscaleFunctionDilateImageFilter, BinaryDilateImageFilter

    C++ includes: itkHConvexImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkHConvexImageFilterIUS3IUS3_Pointer":
        """__New_orig__() -> itkHConvexImageFilterIUS3IUS3_Pointer"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUS3IUS3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkHConvexImageFilterIUS3IUS3_Pointer":
        """Clone(itkHConvexImageFilterIUS3IUS3 self) -> itkHConvexImageFilterIUS3IUS3_Pointer"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUS3IUS3_Clone(self)


    def SetHeight(self, _arg: 'unsigned short const') -> "void":
        """
        SetHeight(itkHConvexImageFilterIUS3IUS3 self, unsigned short const _arg)

        Set/Get the height that a
        local maximum must be above the local background (local contrast) in
        order to survive the processing. Local maxima below this value are
        replaced with an estimate of the local background. 
        """
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUS3IUS3_SetHeight(self, _arg)


    def GetHeight(self) -> "unsigned short":
        """GetHeight(itkHConvexImageFilterIUS3IUS3 self) -> unsigned short"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUS3IUS3_GetHeight(self)


    def SetFullyConnected(self, _arg: 'bool const') -> "void":
        """
        SetFullyConnected(itkHConvexImageFilterIUS3IUS3 self, bool const _arg)

        Set/Get whether
        the connected components are defined strictly by face connectivity or
        by face+edge+vertex connectivity. Default is FullyConnectedOff. For
        objects that are 1 pixel wide, use FullyConnectedOn. 
        """
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUS3IUS3_SetFullyConnected(self, _arg)


    def GetFullyConnected(self) -> "bool const &":
        """GetFullyConnected(itkHConvexImageFilterIUS3IUS3 self) -> bool const &"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUS3IUS3_GetFullyConnected(self)


    def FullyConnectedOn(self) -> "void":
        """FullyConnectedOn(itkHConvexImageFilterIUS3IUS3 self)"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUS3IUS3_FullyConnectedOn(self)


    def FullyConnectedOff(self) -> "void":
        """FullyConnectedOff(itkHConvexImageFilterIUS3IUS3 self)"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUS3IUS3_FullyConnectedOff(self)

    InputEqualityComparableCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterIUS3IUS3_InputEqualityComparableCheck
    IntConvertibleToInputCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterIUS3IUS3_IntConvertibleToInputCheck
    InputOStreamWritableCheck = _itkHConvexImageFilterPython.itkHConvexImageFilterIUS3IUS3_InputOStreamWritableCheck
    __swig_destroy__ = _itkHConvexImageFilterPython.delete_itkHConvexImageFilterIUS3IUS3

    def cast(obj: 'itkLightObject') -> "itkHConvexImageFilterIUS3IUS3 *":
        """cast(itkLightObject obj) -> itkHConvexImageFilterIUS3IUS3"""
        return _itkHConvexImageFilterPython.itkHConvexImageFilterIUS3IUS3_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkHConvexImageFilterIUS3IUS3

        Create a new object of the class itkHConvexImageFilterIUS3IUS3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkHConvexImageFilterIUS3IUS3.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkHConvexImageFilterIUS3IUS3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkHConvexImageFilterIUS3IUS3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkHConvexImageFilterIUS3IUS3.Clone = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIUS3IUS3_Clone, None, itkHConvexImageFilterIUS3IUS3)
itkHConvexImageFilterIUS3IUS3.SetHeight = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIUS3IUS3_SetHeight, None, itkHConvexImageFilterIUS3IUS3)
itkHConvexImageFilterIUS3IUS3.GetHeight = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIUS3IUS3_GetHeight, None, itkHConvexImageFilterIUS3IUS3)
itkHConvexImageFilterIUS3IUS3.SetFullyConnected = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIUS3IUS3_SetFullyConnected, None, itkHConvexImageFilterIUS3IUS3)
itkHConvexImageFilterIUS3IUS3.GetFullyConnected = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIUS3IUS3_GetFullyConnected, None, itkHConvexImageFilterIUS3IUS3)
itkHConvexImageFilterIUS3IUS3.FullyConnectedOn = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIUS3IUS3_FullyConnectedOn, None, itkHConvexImageFilterIUS3IUS3)
itkHConvexImageFilterIUS3IUS3.FullyConnectedOff = new_instancemethod(_itkHConvexImageFilterPython.itkHConvexImageFilterIUS3IUS3_FullyConnectedOff, None, itkHConvexImageFilterIUS3IUS3)
itkHConvexImageFilterIUS3IUS3_swigregister = _itkHConvexImageFilterPython.itkHConvexImageFilterIUS3IUS3_swigregister
itkHConvexImageFilterIUS3IUS3_swigregister(itkHConvexImageFilterIUS3IUS3)

def itkHConvexImageFilterIUS3IUS3___New_orig__() -> "itkHConvexImageFilterIUS3IUS3_Pointer":
    """itkHConvexImageFilterIUS3IUS3___New_orig__() -> itkHConvexImageFilterIUS3IUS3_Pointer"""
    return _itkHConvexImageFilterPython.itkHConvexImageFilterIUS3IUS3___New_orig__()

def itkHConvexImageFilterIUS3IUS3_cast(obj: 'itkLightObject') -> "itkHConvexImageFilterIUS3IUS3 *":
    """itkHConvexImageFilterIUS3IUS3_cast(itkLightObject obj) -> itkHConvexImageFilterIUS3IUS3"""
    return _itkHConvexImageFilterPython.itkHConvexImageFilterIUS3IUS3_cast(obj)


import itkHelpers
@itkHelpers.accept_numpy_array_like_xarray
def h_convex_image_filter(*args, **kwargs):
    """Procedural interface for HConvexImageFilter"""
    import itk
    instance = itk.HConvexImageFilter.New(*args, **kwargs)
    return instance.__internal_call__()

def h_convex_image_filter_init_docstring():
    import itk
    import itkTemplate
    import itkHelpers
    if isinstance(itk.HConvexImageFilter, itkTemplate.itkTemplate):
        filter_object = itk.HConvexImageFilter.values()[0]
    else:
        filter_object = itk.HConvexImageFilter

    h_convex_image_filter.__doc__ = filter_object.__doc__
    h_convex_image_filter.__doc__ += "\n Args are Input(s) to the filter.\n"
    h_convex_image_filter.__doc__ += "Available Keyword Arguments:\n"
    h_convex_image_filter.__doc__ += "".join([
        "  " + itkHelpers.camel_to_snake_case(item[3:]) + "\n"
        for item in dir(filter_object)
        if item[:3] == "Set"])



