
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-05T17:00:54+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "255aa122bfe9300daa40628de0d99931f78bf376",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
