
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "315bea6f483b0f838ed07e10a4bc4323cdce9747",
 "version": "1.1.26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
