BASE_HTTP_LATENCY_METRIC_NAME = 'http_requests_duration_ms'
BASE_HTTP_COUNTER_METRIC_NAME = 'http_requests_total'
BASE_HTTP_LATENCY_GAUGE_METRIC_NAME = 'http_requests_duration_total_ms'
BASE_EXTERNAL_IO_DURATION_METRIC_NAME = 'external_io_duration_ms'
BASE_EXTERNAL_IO_LATENCY_GAUGE_METRIC = 'external_io_duration_total_ms'
BASE_EXTERNAL_IO_COUNTER_METRIC_NAME = 'external_io_total'
BASE_FUNCTION_DURATION_METRIC_NAME = 'function_duration_ms'

BASE_HTTP_EXCEPTION_METRIC = 'http_requests_exception_type'
BASE_EXTERNAL_IO_EXCEPTION_METRIC = 'external_io_exception_type'
BASE_FUNCTION_EXCEPTION_METRIC = 'function_exception_type'
BASE_FUNCTION_LATENCY_GAUGE_METRIC = 'function_duration_total_ms'

BASE_BYTES_METRIC = 'bytes_size'
BASE_REQUEST_PATH_DURATION_METRIC = 'http_requests_path_duration_ms'

METRIC_NAME_SEPERATOR = '.'
METRIC_LABEL_SEPERATOR = '.'
METRIC_NO_MAPPING_LABEL_EQUAL = '='
METRIC_NO_MAPPING_LABEL_SEPERATOR = ','
METRIC_NO_MAPPING_LABEL_PREFIX = '#'

HTTP_REQUEST_STATUS_CODE_OPTIONS = range(200, 599)
FUNCTION_STATUS_VALUES = ['success', 'error']

METRIC_APP_NAME_VAR_NAME = 'METRIC_APP_NAME'

TAG_REDIS = 'REDIS'
TAG_MYSQL = 'MYSQL'
TAG_MEMCACHE = 'MEMCACHE'
TAG_API = 'API'
TAG_ELASTICSEARCH = 'ELASTICSEARCH'
TAG_OTHER = 'TAG_OTHER'
