# Generated by Django 2.2.5 on 2019-09-23 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('sites_microsoft_auth', '0002_auto_20190923_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsoftaccount',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='xboxliveaccount',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
