# Generated by Django 2.2.2 on 2019-07-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tom_education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutovarProcess',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tom_education.pipelineprocess',),
        ),
    ]
