
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-28T13:02:19+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8b8361ce946ea70ed01becfd0fd176b6304a99ae",
 "version": "0.0.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
