the_game = ["Life Fighter consiste una una grilla del",
            "Juego de la Vida de Conway en la cual una",
            "poblacion de celulas va evolucionando.",
            "Algunas nacen, otras mueren y otras sobreviven.",
            "",
            "Una de las celulas es el nuestro heroe y el",
            "objetivo es moverlo a una posicion segura que",
            "le permita pasar a la siguiente generacion.",
            "",
            "Distintos modos de juego estan disponibles.",
            "Mas informacion en https://github.com/jjconti/life-fighter",]

the_rules = ["Cada celula puede estar viva (casilla rellena)",
             "o puede estar muerta (casilla vacia),",
             "y cada una tiene exactamente 8 vecinas.",
             "",
             "1 - Si una celula esta viva y tiene menos de",
             "2 vecinas vivas, muere de soledad.",
             "",
             "2 - Si una celula esta viva y tiene mas de 3",
             "vecinas vivas, muere por sobrepoblacion.",
             "",
             "3 - Una celula muerta con 3 vecina vivas, nace.",]

controls = ["SPACE BAR: siempre provoca un paso de",
            "generacion. Se aplican las reglas de evolucion.",
            "",
            "N: provoca un cambio de nivel y",
            "un paso de generacion.",]

the_credits = ["Este juego es desarrollado por Juan Jose Conti",
               "mail: jjconti AT gnu.org",
               "blog: http://www.juanjoconti.com.ar",
               "",
               "Este es un juego libre. Esta licenciado con",
               "la licencia publica de GNU (GPL).",
               "",
               "Gracias a PyAr (http://www.python.org/ar) por",
               "ayudarme con pygame y python en general.",
               "",
               "Los sonidos son de http://freesound.iua.upf.edu/",]
