# Generated by Django 2.2.2 on 2019-07-30 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_education', '0001_initial'),
        ('tom_astrosource', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutovarProcess',
        ),
        migrations.CreateModel(
            name='AstrosourceProcess',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tom_education.pipelineprocess',),
        ),
    ]
