
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-03T17:20:57+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f5eb84f594ebf472fa453393a98bb089ffac1ee0",
 "version": "v20.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
