"""add offline installation fields

Revision ID: 0688ae3baa88
Revises: 6f0d7d321e8b
Create Date: 2019-03-18 10:44:49.617091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0688ae3baa88'
down_revision = '6f0d7d321e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appconfig', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gluu_archive', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('offline', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appconfig', schema=None) as batch_op:
        batch_op.drop_column('offline')
        batch_op.drop_column('gluu_archive')

    # ### end Alembic commands ###
