
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-03T08:16:09+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "81de5d28533978f9e2fddf6a98a96afcd14d7e75",
 "version": "0.2.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
