# Generated by Django 2.2.5 on 2020-03-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_microsoft_auth', '0007_auto_20200112_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='attribute_mappings',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='sync_user_attributes',
            field=models.BooleanField(default=False),
        ),
    ]
